require("dotenv").config(); // must be at top
const mongoose = require("mongoose");
const Product = require("./models/product"); // your Product model

const mongoURI = process.env.MONGO_URI;

const BeautyProducts = [
  {
    name: "Renee Everyday Primer & Makeup Combo",
    description:
      "Renee Everyday Mattifying Primer, Makeup and Bollywood Filter face powder.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 1200,
    discount: 30,
    price: 840,
    imageUrl: "https://i.ibb.co/Rk8GxnhC/bty1.png",
    inStock: false,
  },
  {
    name: "Bamboo Makeup Brush Set",
    description: "Bamboo cosmetic makeup brush set with multiple brushes.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 450,
    discount: 20,
    price: 360,
    imageUrl: "https://i.ibb.co/60v0sbNd/bty2.png",
    inStock: true,
  },
  {
    name: "Lakme 9 to 5 CC Cream",
    description:
      "Lakme 9 to 5 CC Complexion Care Cream with SPF 30 for even skin.",
    category: "Beauty",
    subCategory: "Face Cream",
    originalPrice: 350,
    discount: 15,
    price: 297.5,
    imageUrl: "https://i.ibb.co/1GfjyvWH/bty3.png",
    inStock: false,
  },
  {
    name: "Vitamin C Serum",
    description: "Brightening serum with concentrated vitamin C.",
    category: "Beauty",
    subCategory: "Serum",
    originalPrice: 999,
    discount: 25,
    price: 749.25,
    imageUrl: "https://i.ibb.co/9HDQvFVk/bty4.webp",
    inStock: true,
  },
  {
    name: "Chanel Mini Handbag",
    description: "Elegant black quilted Chanel mini handbag with gold chain.",
    category: "Beauty",
    subCategory: "Handbag",
    originalPrice: 599,
    discount: 20,
    price: 479.2,
    imageUrl: "https://i.ibb.co/whgTcXHn/bty5.png",
    inStock: false,
  },
  {
    name: "Swiss Beauty Natural Makeup",
    description:
      "Long-lasting makeup fixing spray enriched with aloe vera and vitamin E.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 550,
    discount: 15,
    price: 467.5,
    imageUrl: "https://i.ibb.co/FqjRZMSJ/bty6.png",
    inStock: true,
  },
  {
    name: "HUDA GIRL Nude & Rose Gold Palette Duo",
    description:
      "High-pigment eyeshadow palettes featuring Nude and Rose Gold shades.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 699,
    discount: 20,
    price: 559.2,
    imageUrl: "https://i.ibb.co/V0FHFS27/bty7.png",
    inStock: false,
  },
  {
    name: "Blue Heaven Complete Makeup Kit",
    description:
      "Comprehensive beauty set including foundation, mascara, eyeliner, lipstick and compact powder.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 450,
    discount: 10,
    price: 405,
    imageUrl: "https://i.ibb.co/qLXGXgpg/bty8.png",
    inStock: true,
  },
  {
    name: "Rose Gold Remastered Eyeshadow Palette",
    description: "Professional 18-shade eyeshadow palette.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 399,
    discount: 15,
    price: 339.15,
    imageUrl: "https://i.ibb.co/hFmdHMTF/bty9.png",
    inStock: false,
  },
  {
    name: "Dove Exfoliate Away Serum Body Wash",
    description:
      "Skin-renewing body wash formulated with 4% brightening serum.",
    category: "Beauty",
    subCategory: "Body Care",
    originalPrice: 799,
    discount: 20,
    price: 639.2,
    imageUrl: "https://i.ibb.co/MyV5jpzY/bty10.png",
    inStock: true,
  },
  {
    name: "Vatenn Italy Italian Matte Foundation",
    description: "Long-lasting 24-hour pro matte finish foundation.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 899,
    discount: 25,
    price: 674.25,
    imageUrl: "https://i.ibb.co/pBBZ6NGy/bty11.png",
    inStock: false,
  },
  {
    name: "PinkLine Switzerland Liquid Lipstick",
    description:
      "High-pigment matte liquid lipstick with smooth long-wearing formula.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 499,
    discount: 20,
    price: 399.2,
    imageUrl: "https://i.ibb.co/84Ms8YmQ/bty12.png",
    inStock: true,
  },
  {
    name: "LUX Rose & Aloe Vera Hand Wash",
    description: "Refreshing hand wash infused with essential oils.",
    category: "Beauty",
    subCategory: "Body Care",
    originalPrice: 399,
    discount: 15,
    price: 339.15,
    imageUrl: "https://i.ibb.co/MD3fSQRv/bty13.png",
    inStock: false,
  },
  {
    name: "Dove Dryness Care Body Wash",
    description: "Sulphate-free moisturizing body wash with jojoba oil.",
    category: "Beauty",
    subCategory: "Body Care",
    originalPrice: 699,
    discount: 25,
    price: 524.25,
    imageUrl: "https://i.ibb.co/cSv6GZ2V/bty14.png",
    inStock: true,
  },
  {
    name: "ESTELAR Matte Compact Powder",
    description:
      "Fine-textured matte compact powder for smooth shine-free complexion.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 299,
    discount: 10,
    price: 269.1,
    imageUrl: "https://i.ibb.co/pjF7QFQj/bty15.png",
    inStock: false,
  },
  {
    name: "Dove Deep Moisture Body Wash",
    description:
      "Gentle 24-hour moisturizing cleanser for softness and nourishment.",
    category: "Beauty",
    subCategory: "Body Care",
    originalPrice: 399,
    discount: 15,
    price: 339.15,
    imageUrl: "https://i.ibb.co/HDFs9pzp/bty16.png",
    inStock: true,
  },
  {
    name: "Indulekha Bringha Hair Oil",
    description:
      "Ayurvedic medicine for hair growth and reduction of hair fall.",
    category: "Beauty",
    subCategory: "Haircare",
    originalPrice: 899,
    discount: 20,
    price: 719.2,
    imageUrl: "https://i.ibb.co/RJRKcd4/bty17.png",
    inStock: false,
  },
  {
    name: "NIVEA Aloe Protection Body Lotion",
    description: "Lightweight body lotion with SPF 15 and Aloe Vera.",
    category: "Beauty",
    subCategory: "Body Care",
    originalPrice: 199,
    discount: 10,
    price: 179.1,
    imageUrl: "https://i.ibb.co/q3r4q7Kw/bty18.png",
    inStock: true,
  },
  {
    name: "LiLash XL Purified Eyelash Serum",
    description: "Premium 4.0 ml eyelash growth serum.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 349,
    discount: 20,
    price: 279.2,
    imageUrl: "https://i.ibb.co/Z16rVcTZ/bty19.png",
    inStock: false,
  },
  {
    name: "Estee Lauder Double Wear Foundation",
    description: "24-hour stay-in-place liquid makeup.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 299,
    discount: 15,
    price: 254.15,
    imageUrl: "https://i.ibb.co/35FmBW6h/bty20.png",
    inStock: true,
  },

  {
    name: "Anastasia Beverly Hills Brow Wiz",
    description: "Ultra-slim retractable eyebrow pencil.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 499,
    discount: 20,
    price: 399.2,
    imageUrl: "https://i.ibb.co/jZRHcf2s/bty21.png",
    inStock: false,
  },
  {
    name: "Charlotte Tilbury Airbrush Flawless Setting Spray",
    description: "Weightless oil-free hydrating setting spray.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 899,
    discount: 25,
    price: 674.25,
    imageUrl: "https://i.ibb.co/sYMg9D4/bty22.png",
    inStock: true,
  },
  {
    name: "Estee Lauder Double Wear Foundation Set",
    description: "Bulk collection of stay-in-place liquid makeup.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 349,
    discount: 10,
    price: 314.1,
    imageUrl: "https://i.ibb.co/yBbcQnHg/bty23.png",
    inStock: false,
  },
  {
    name: "YSL Make Me Blush",
    description: "Yves Saint Laurent liquid-to-powder blurring blush.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 1200,
    discount: 20,
    price: 960,
    imageUrl: "https://i.ibb.co/5gwDTTQz/bty24.png",
    inStock: true,
  },
  {
    name: "Rodan + Fields Lash Boost",
    description: "Nightly eyelash conditioning serum.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 499,
    discount: 15,
    price: 424.15,
    imageUrl: "https://i.ibb.co/Fk6RfMtn/bty25.png",
    inStock: false,
  },
  {
    name: "bareMinerals SPF 20 Concealer - Summer Bisque",
    description: "Mineral-based concealer with SPF 20.",
    category: "Beauty",
    subCategory: "Concealer",
    originalPrice: 699,
    discount: 20,
    price: 559.2,
    imageUrl: "https://i.ibb.co/RLDnn8N/bty26.png",
    inStock: true,
  },
  {
    name: "Younique Moodstruck Epic 4D Mascara",
    description: "One-step fiber mascara.",
    category: "Beauty",
    subCategory: "Mascara",
    originalPrice: 599,
    discount: 15,
    price: 509.15,
    imageUrl: "https://i.ibb.co/jkn4rFzx/bty27.png",
    inStock: false,
  },
  {
    name: "RENEE Color Lock Transfer Not Crayon",
    description: "Richly pigmented lip crayon.",
    category: "Beauty",
    subCategory: "Lip Crayon",
    originalPrice: 399,
    discount: 10,
    price: 359.1,
    imageUrl: "https://i.ibb.co/23NG8s8W/bty28.png",
    inStock: true,
  },
  {
    name: "Dior Addict Lip Maximizer",
    description: "Lip plumping gloss.",
    category: "Beauty",
    subCategory: "Lip Gloss",
    originalPrice: 349,
    discount: 15,
    price: 296.65,
    imageUrl: "https://i.ibb.co/zVtCwDp3/bty29.png",
    inStock: false,
  },
  {
    name: "Bella Vita Intense Drama Kajal",
    description: "Richly pigmented black kajal pencil.",
    category: "Beauty",
    subCategory: "Eyeliner",
    originalPrice: 499,
    discount: 20,
    price: 399.2,
    imageUrl: "https://i.ibb.co/vv4GVX0C/bty30.png",
    inStock: true,
  },

  {
    name: "Ultimate 40-Piece Professional Makeup Palette",
    description: "Comprehensive all-in-one vanity kit.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 699,
    discount: 25,
    price: 524.25,
    imageUrl: "https://i.ibb.co/xqfsXhfW/bty31.png",
    inStock: false,
  },
  {
    name: "Luxara 15-Piece Rose Gold Brush Collection",
    description: "Professional-grade synthetic brush set.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 299,
    discount: 10,
    price: 269.1,
    imageUrl: "https://i.ibb.co/V07zNMDg/bty32.png",
    inStock: true,
  },
  {
    name: "Rose of No Man's Land Travel Cosmetic Organizer",
    description: "Premium vegan leather travel bag.",
    category: "Beauty",
    subCategory: "Bags & Cases",
    originalPrice: 199,
    discount: 15,
    price: 169.15,
    imageUrl: "https://i.ibb.co/GvjqQwZj/bty33.png",
    inStock: false,
  },
  {
    name: "Acrylic Cosmetic Organizer",
    description: "Clear acrylic organizer with multiple compartments.",
    category: "Beauty",
    subCategory: "Storage & Organizers",
    originalPrice: 149,
    discount: 10,
    price: 134.1,
    imageUrl: "https://i.ibb.co/m5rQLYVC/bty34.png",
    inStock: true,
  },
  {
    name: "Auric Vibrant Pink Lipstick",
    description: "Bold high-pigment lipstick in vibrant pink.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 299,
    discount: 15,
    price: 254.15,
    imageUrl: "https://i.ibb.co/yF26D16p/bty35.png",
    inStock: false,
  },
  {
    name: "HUDA Girl Air Pad CC Cream",
    description: "Compact CC cream with perforated powder design.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 599,
    discount: 20,
    price: 479.2,
    imageUrl: "https://i.ibb.co/My8BFS5N/bty36.png",
    inStock: true,
  },
  {
    name: "Liquid Highlighter - Light Pink",
    description: "Shimmering liquid highlighter with dropper.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 399,
    discount: 15,
    price: 339.15,
    imageUrl: "https://i.ibb.co/Mx6FtqBD/bty37.png",
    inStock: false,
  },
  {
    name: "Charlotte Tilbury Airbrush Flawless Finish Powder",
    description: "Luxury micro-powder compact.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 799,
    discount: 20,
    price: 639.2,
    imageUrl: "https://i.ibb.co/0VdMJyWy/bty38.png",
    inStock: true,
  },
  {
    name: "NIVEA Soft Moisturizing Cream - Pomegranate",
    description: "Refreshing multi-purpose cream.",
    category: "Beauty",
    subCategory: "Skincare",
    originalPrice: 599,
    discount: 15,
    price: 509.15,
    imageUrl: "https://i.ibb.co/7tgnfryh/bty39.png",
    inStock: false,
  },
  {
    name: "The Face Shop Teatree Pore Clarifying Gel Cleanser",
    description: "Gentle gel cleanser infused with teatree.",
    category: "Beauty",
    subCategory: "Skincare",
    originalPrice: 399,
    discount: 10,
    price: 359.1,
    imageUrl: "https://i.ibb.co/jPGYW7tB/bty40.png",
    inStock: true,
  },

  {
    name: "SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule",
    description: "Brightening ampoule infused with Centella.",
    category: "Beauty",
    subCategory: "Skincare",
    originalPrice: 499,
    discount: 15,
    price: 424.15,
    imageUrl: "https://i.ibb.co/bR58tSn7/bty41.png",
    inStock: false,
  },
  {
    name: "Water Fit Tint - Deep Red",
    description: "Lightweight water-based lip tint.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 299,
    discount: 10,
    price: 269.1,
    imageUrl: "https://i.ibb.co/Rp3vL9dX/bty42.png",
    inStock: true,
  },
  {
    name: "Huda Beauty Easy Bake Loose Setting Powder",
    description: "Finely milled loose powder with mesh sifter.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 699,
    discount: 20,
    price: 559.2,
    imageUrl: "https://i.ibb.co/67THcMff/bty43.png",
    inStock: false,
  },
  {
    name: "Daily Life Forever52 Ultra Definition Liquid Foundation",
    description: "Pump-bottle liquid foundation.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 249,
    discount: 10,
    price: 224.1,
    imageUrl: "https://i.ibb.co/cKWKtNPV/bty44.png",
    inStock: true,
  },
  {
    name: "Daily Life Forever52 Complete Coverage Concealer",
    description: "Professional liquid concealer.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 599,
    discount: 15,
    price: 509.15,
    imageUrl: "https://i.ibb.co/q3sv1TSf/bty45.png",
    inStock: false,
  },
  {
    name: "Minimalist Vitamin C 10% Face Serum",
    description: "Brightening serum with acetyl glucosamine.",
    category: "Beauty",
    subCategory: "Skincare",
    originalPrice: 299,
    discount: 10,
    price: 269.1,
    imageUrl: "https://i.ibb.co/nN3bs0KK/bty46.png",
    inStock: true,
  },
  {
    name: "Swiss Beauty Airbrush Finish Full Coverage Foundation",
    description: "Full coverage foundation with hyaluronic acid.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 399,
    discount: 15,
    price: 339.15,
    imageUrl: "https://i.ibb.co/5gykqRPG/bty47.png",
    inStock: false,
  },
  {
    name: "Swiss Beauty Precision Thickening Long Lash Mascara",
    description: "Lash defining mascara.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 199,
    discount: 10,
    price: 179.1,
    imageUrl: "https://i.ibb.co/mCCJphtS/bty48.png",
    inStock: true,
  },
  {
    name: "Swiss Beauty Cream It Up Blush with Shea Butter",
    description: "Highly pigmented long-lasting cream blush.",
    category: "Beauty",
    subCategory: "Makeup",
    originalPrice: 899,
    discount: 20,
    price: 719.2,
    imageUrl: "https://i.ibb.co/1tPkphJr/bty49.png",
    inStock: false,
  },
  {
    name: "Chemist at Play Cherry Lip Jelly SPF 50 PA++++",
    description: "Cherry flavored lip jelly with SPF 50 protection.",
    category: "Beauty",
    subCategory: "Lip Care",
    originalPrice: 999,
    discount: 25,
    price: 749.25,
    imageUrl: "https://i.ibb.co/GfSKdbXv/bty50.png",
    inStock: true,
  },
];

async function seedBeautyProducts() {
  try {
    await mongoose.connect(mongoURI);
    console.log("✅ MongoDB connected");

    await Product.deleteMany({ category: /Beauty/i }); // delete old beauty products
    await Product.insertMany(BeautyProducts);
    console.log("✅ Beauty products seeded successfully");
  } catch (err) {
    console.error("❌ Error seeding beauty products:", err);
  } finally {
    await mongoose.connection.close();
  }
}

seedBeautyProducts();
