require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/product");

const mongoURI = process.env.MONGO_URI;

mongoose
  .connect(mongoURI)
  .then(() => console.log("✅ MongoDB connected successfully"))
  .catch((err) => console.error("❌ MongoDB connection error:", err));

  const KidsProducts = [
    {
      name: "Kids Kurta Pyjama Set",
      description: "Boys Festive & Party Kurta and Pyjama Set (Blue Pack of 1)",
      category: "Kids",
      subCategory: "Kurta Pyjama",
      originalPrice: 499,
      discount: 20,
      price: 399,
      imageUrl: "https://i.ibb.co/pBBRLJCk/kid1.png",
      inStock: true,
      color: "Blue",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Kurta Pyjama Set",
      description: "Boys Festive & Party Kurta and Pyjama Set",
      category: "Kids",
      subCategory: "Kurta Pyjama",
      originalPrice: 699,
      discount: 15,
      price: 594,
      imageUrl: "https://i.ibb.co/35t0fhjc/kid2.png",
      inStock: false,
      color: "Blue",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids Dungaree",
      description: "Dungaree For Boys & Girls Printed, Applique Denim",
      category: "Kids",
      subCategory: "Dungaree",
      originalPrice: 799,
      discount: 25,
      price: 599,
      imageUrl: "https://i.ibb.co/k2rGhhCW/kid3.png",
      inStock: true,
      color: "Yellow",  
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt",
      description:
        "Boys Graphic Print Polyester Regular T-Shirt (Multicolor, Pack of 4)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 599,
      discount: 10,
      price: 539,
      imageUrl: "https://i.ibb.co/ymPnNm9P/kid4.png",
      inStock: true,
      color: ["Green", "Purple", "Red", "Pink"],
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids T-Shirt",
      description:
        "Boys Graphic Print Polyester Regular T-Shirt (Multicolor, Pack of 4)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 449,
      discount: 0,
      price: 449,
      imageUrl: "https://i.ibb.co/JjqT2LhN/kid5.png",
      inStock: false,
      color: ["Black", "Red", "Yellow", "Blue"],
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Kurta Pyjama Set",
      description: "Boys Festive & Party Kurta and Pyjama Set",
      category: "Kids",
      subCategory: "Kurta Pyjama",
      originalPrice: 899,
      discount: 20,
      price: 719,
      imageUrl: "https://i.ibb.co/hFPMj2rX/kid6.png",
      inStock: true,
      color: "Pink",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Casual Shirts",
      description: "Boys Regular Fit Printed Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 199,
      discount: 10,
      price: 179,
      imageUrl: "https://i.ibb.co/27mk6c9H/kid7.png",
      inStock: true,
      color: "Black",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids Nightwear",
      description:
        "Baby Girls Printed Cotton Blend Kids Nightwear (Black Pack of 1)",
      category: "Kids",
      subCategory: "Nightwear",
      originalPrice: 1299,
      discount: 15,
      price: 1104,
      imageUrl: "https://i.ibb.co/mFgwFSyD/kid8.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Casual Shirt",
      description: "Boys Regular Fit Printed Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 1499,
      discount: 25,
      price: 1124,
      imageUrl: "https://i.ibb.co/cSGcLRw6/kid9.png",
      inStock: true,
      color: "Yellow",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Casual Shirt",
      description:
        "Boys Regular Fit Striped, Floral Print Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/mV0wjrSJ/kid10.png",
      inStock: true,
      color: "Beige",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Casual Shirt",
      description:
        "Boys Regular Fit Striped, Floral Print Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 799,
      discount: 20,
      price: 639,
      imageUrl: "https://i.ibb.co/KjdXnPKp/kid11.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids Casual Shirt",
      description: "Boys Regular Fit Printed Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 499,
      discount: 15,
      price: 424,
      imageUrl: "https://i.ibb.co/Fktx648Z/kid12.png",
      inStock: true,
      color: "Black",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Regular T-Shirt",
      description:
        "Boys & Girls Cartoon Polycotton Regular T Shirt (Black, Pack of 1)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/bjWzxZZr/kid13.png",
      inStock: true,
      color: "Black",
      size: "9 - 12 Years",
    },
    {
      name: "Kids Shirt",
      description: "Boys Relaxed Fit Fit Printed Lapel Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 799,
      discount: 20,
      price: 639,
      imageUrl: "https://i.ibb.co/JF35YDqT/kid14.png",
      inStock: false,
      color: "Blue",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Shirt",
      description: "Boys Regular Fit Striped, Printed Spread Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 699,
      discount: 15,
      price: 594,
      imageUrl: "https://i.ibb.co/TMsSvZJQ/kid15.png",
      inStock: true,
      color: "White",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids Shirt",
      description: "Boy Regular Fit Printed Slim Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 599,
      discount: 10,
      price: 539,
      imageUrl: "https://i.ibb.co/d4DXdGxn/kid16.webp",
      inStock: true,
      color: "White",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Shirt",
      description: "Boy Regular Fit Printed Slim Collar Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 799,
      discount: 20,
      price: 639,
      imageUrl: "https://i.ibb.co/MkdpwSc1/kid17.webp",
      inStock: false,
      color: "Pink",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt",
      description:
        "Baby Boys Printed Cotton Blend Regular T Shirt(Black, Pack of 1)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 999,
      discount: 15,
      price: 849,
      imageUrl: "https://i.ibb.co/zhH6DQhG/kid18.webp",
      inStock: true,
      color: "Black",
      size: "3 - 6 Years",
    },
    {
      name: "Kids T Shirt & Pant Set",
      description: "Boy & Girl Cotton Regular Fit T Shirt & Pant Set",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 499,
      discount: 10,
      price: 449,
      imageUrl: "https://i.ibb.co/mFV7bnhx/kid19.png",
      inStock: true,
      color: "Black",
      size: "9 - 12 Years",
    },
    {
      name: "Kids Sweatshirt",
      description: "Boys Full Sleeve Printed Sweatshirt",
      category: "Kids",
      subCategory: "Sweatshirt",
      originalPrice: 399,
      discount: 0,
      price: 399,
      imageUrl: "https://i.ibb.co/wNsm0xmB/kid20.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Maxi",
      description: "Girls Maxi/Full Length Party Dress(Red, Sleeveless)",
      category: "Kids",
      subCategory: "Maxi",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/ZzcRjp1C/kid21.png",
      inStock: true,
      color: "Red",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Dungaree",
      description:
        "Dungaree For Baby Boys & Baby Girls Casual Checkered Cotton Blend",
      category: "Kids",
      subCategory: "Dungaree",
      originalPrice: 1299,
      discount: 20,
      price: 1039,
      imageUrl: "https://i.ibb.co/RGnn9RH9/kid22.png",
      inStock: true,
      color: "Black",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Shirt & Pant Set",
      description: "Baby Boys Part(Festive) Shirt Pant(White)",
      category: "Kids",
      subCategory: "Dress",
      originalPrice: 899,
      discount: 15,
      price: 764,
      imageUrl: "https://i.ibb.co/275RzH7r/kid23.png",
      inStock: false,
      color: "White",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids T Shirt Shorts",
      description: "Boys Casual T-Shirt Short (Navy All)",
      category: "Kids",
      subCategory: "Shorts",
      originalPrice: 499,
      discount: 10,
      price: 449,
      imageUrl: "https://i.ibb.co/TxNbfQvW/kid24.png",
      inStock: true,
      color: "Blue",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T Shirt Shorts",
      description: "Baby Boys Casual T-Shirt Shorts (Blue)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 299,
      discount: 0,
      price: 299,
      imageUrl: "https://i.ibb.co/9k4bd0VQ/kid25.png",
      inStock: true,
      color: "Blue",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt Jeans",
      description: "Boys Casual T-Shirt Jeans (Brown)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 699,
      discount: 20,
      price: 559,
      imageUrl: "https://i.ibb.co/JjpDXgMF/kid26.png",
      inStock: false,
      color: "Brown",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids T-Shirt Set",
      description: "Baby Boys Full Sleeves Casual T-Shirt Pant( Multicolor)",
      category: "Kids",
      subCategory: "Set",
      originalPrice: 799,
      discount: 15,
      price: 679,
      imageUrl: "https://i.ibb.co/BKwbHs3B/kid27.png",
      inStock: true,
      color: ["Grey", "Black"],
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Jumpsuit",
      description: "Solid Girls Jumpsuit",
      category: "Kids",
      subCategory: "Jumpsuit",
      originalPrice: 599,
      discount: 10,
      price: 539,
      imageUrl: "https://i.ibb.co/d0CDnrbS/kid28.png",
      inStock: true,
      color: "Aqua",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Top Bottom",
      description: "Baby Girls Party ( Festive ) Top & Bottom",
      category: "Kids",
      subCategory: "Dress",
      originalPrice: 199,
      discount: 0,
      price: 199,
      imageUrl: "https://i.ibb.co/9kz1NzFQ/kid29.png",
      inStock: false,
      color: "Yellow",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt Set",
      description: "Boys & Girls Casual T-Shirt Shorts (Multicolor - 3)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/7NnfvpGn/kid30.png",
      inStock: true,
      color: ["Yellow", "Pink", "Black"],
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Sweatshirt",
      description: "Boys Casual Sweatshirt Set (Multicolor - 3)",
      category: "Kids",
      subCategory: "Sweatshirt",
      originalPrice: 999,
      discount: 20,
      price: 799,
      imageUrl: "https://i.ibb.co/Mkz6yR0N/kid31.png",
      inStock: true,
      color: ["Pink", "Green", "Blue"],
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids T-Shirt Set",
      description: "Boys Cotton T-Shirt & Pant Set",
      category: "Kids",
      subCategory: "Dress",
      originalPrice: 899,
      discount: 15,
      price: 764,
      imageUrl: "https://i.ibb.co/sJzVN83p/kid32.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years , 9 - 12 Years",
    },
    {
      name: "Kids Regular T-Shirt",
      description:
        "Boys Colorblock Cotton Blend Regular T-Shirt (Blue, Pack of 1)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 1299,
      discount: 10,
      price: 1169,
      imageUrl: "https://i.ibb.co/bgdFJpc2/kid33.png",
      inStock: true,
      color: "Blue",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Formal Shirt",
      description: "Boys Regular Fit Cotton Collar Spread Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 799,
      discount: 20,
      price: 639,
      imageUrl: "https://i.ibb.co/mrtsMVJ5/kid34.png",
      inStock: true,
      color: "Aqua",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Regular T-Shirt",
      description: "Baby Boys & Baby Girls Printed Cotton Blend Regular T Shirt",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 799,
      discount: 15,
      price: 679,
      imageUrl: "https://i.ibb.co/npxSWTg/kid35.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years",
    },
    {
      name: "Kids Sweatshirt",
      description: "Stylish Boy & Girl Sweatshirt (Multicolor, Pack of 2)",
      category: "Kids",
      subCategory: "Sweatshirt",
      originalPrice: 999,
      discount: 20,
      price: 799,
      imageUrl: "https://i.ibb.co/Nn6CLWfx/kid36.png",
      inStock: true,
      color: ["Grey", "Red"],
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Kurta Set",
      description: "Boys Festive & Party Kurta, Waistcoat and Pyjama Set",
      category: "Kids",
      subCategory: "Kurta",
      originalPrice: 499,
      discount: 10,
      price: 449,
      imageUrl: "https://i.ibb.co/Xr1wSYyt/kid37.png",
      inStock: true,
      color: "Aqua",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Dress",
      description: "Girls Cotton Shirt & Pyjama Set",
      category: "Kids",
      subCategory: "Dress",
      originalPrice: 899,
      discount: 15,
      price: 764,
      imageUrl: "https://i.ibb.co/60NBX0Hn/kid38.png",
      inStock: false,
      color: "Pink",
      size: "9 - 12 Years",
    },
    {
      name: "Kids T-Shirt",
      description:
        "Boys Printed V Neck Cotton Blend T-Shirt (Multicolor, Pack of 4)",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 799,
      discount: 10,
      price: 719,
      imageUrl: "https://i.ibb.co/LDc0xdfX/kid39.png",
      inStock: true,
      color: ["Black", "White"],
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Lehenga",
      description:
        "Indi Girls Lehenga Choli Embroidered Lehenga, Choli and Dupatta Set",
      category: "Kids",
      subCategory: "Lehenga",
      originalPrice: 299,
      discount: 0,
      price: 299,
      imageUrl: "https://i.ibb.co/4wJy9hKd/kid40.png",
      inStock: true,
      color: "Red",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt",
      description: "Baby Boys Printed Cotton Blend Regular T Shirt",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 399,
      discount: 10,
      price: 359,
      imageUrl: "https://i.ibb.co/kWKrqzT/kid41.png",
      inStock: false,
      color: "Blue",
      size: "3 - 6 Years",
    },
    {
      name: "Kids Top & Bottom",
      description: "Girls Casual T-Shirt & Pant Set",
      category: "Kids",
      subCategory: "Dress",
      originalPrice: 499,
      discount: 15,
      price: 424,
      imageUrl: "https://i.ibb.co/Q3cL3tsy/kid42.png",
      inStock: true,
      color: "Pink",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Dress",
      description: "Baby Girls Cotton Blend Frock",
      category: "Kids",
      subCategory: "Frock",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/ymng3sZg/kid43.png",
      inStock: true,
      color: "Blue",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Kurta",
      description: "Boys Festive & Party Kurta and Pyjama Set",
      category: "Kids",
      subCategory: "Kurta",
      originalPrice: 699,
      discount: 20,
      price: 559,
      imageUrl: "https://i.ibb.co/Zzb2GYZ9/kid44.png",
      inStock: true,
      color: "Red",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Casual Shirt",
      description: "Boys Full Sleeve Printed Casual Shirt",
      category: "Kids",
      subCategory: "Shirt",
      originalPrice: 499,
      discount: 15,
      price: 424,
      imageUrl: "https://i.ibb.co/67S0gVHZ/kid45.png",
      inStock: false,
      color: "Black",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids T-Shirt",
      description: "Girls Printed Cotton Blend Regular T Shirt",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 299,
      discount: 10,
      price: 269,
      imageUrl: "https://i.ibb.co/tMkGxWP1/kid46.png",
      inStock: true,
      color: "Green",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Pant Set",
      description: "Boys Casual Pant Set (Navy Blue)",
      category: "Kids",
      subCategory: "Pant",
      originalPrice: 399,
      discount: 5,
      price: 379,
      imageUrl: "https://i.ibb.co/DPGT9KZD/kid47.png",
      inStock: true,
      color: "Blue",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids T-Shirt",
      description: "Baby Boys Printed Cotton Blend Regular T Shirt",
      category: "Kids",
      subCategory: "T-Shirt",
      originalPrice: 499,
      discount: 10,
      price: 449,
      imageUrl: "https://i.ibb.co/MrsX1BX/kid48.png",
      inStock: true,
      color: "Green",
      size: "3 - 6 Years , 6 - 9 Years",
    },
    {
      name: "Kids Casual Pants",
      description: "Boys Cotton Blend Pants",
      category: "Kids",
      subCategory: "Pant",
      originalPrice: 299,
      discount: 5,
      price: 284,
      imageUrl: "https://i.ibb.co/bgsMYfnp/kid49.png",
      inStock: true,
      color: "Beige",
      size: "6 - 9 Years , 9 - 12 Years",
    },
    {
      name: "Kids Pant Set",
      description: "Boys Casual Pant & T-Shirt Set",
      category: "Kids",
      subCategory: "Pant",
      originalPrice: 699,
      discount: 15,
      price: 594,
      imageUrl: "https://i.ibb.co/TDCVyZr3/kid50.png",
      inStock: true,
      color: "Grey",
      size: "3 - 6 Years , 6 - 9 Years , 9 - 12 Years",
    },
  ];

async function seedKidsProducts() {
  try {
    console.log("🌀 Deleting old kids products...");
    await Product.deleteMany({ category: "Kids" });

    console.log(`🌀 Inserting ${KidsProducts.length} kids products...`);
    let insertedCount = 0;

    for (const product of KidsProducts) {
      try {
        const inserted = await Product.create(product);
        console.log(`✅ Inserted: ${inserted.name}`);
        insertedCount++;
      } catch (err) {
        console.error(`❌ Failed to insert ${product.name}:`, err.message);
      }
    }

    console.log(
      `\n🎯 Total inserted: ${insertedCount} / ${KidsProducts.length}`,
    );
    console.log("Array length:", KidsProducts.length);
  } catch (err) {
    console.error("❌ Error during seeding:", err);
  } finally {
    mongoose.connection.close();
  }
}

seedKidsProducts();
