
// server/seedProductsElectronics.js
const mongoose = require("mongoose");
const Product = require("./models/product"); // make sure path is correct
require("dotenv").config();

const MONGO_URI = process.env.MONGO_URI;

const ElectronicsProducts = [
  {
    name: "Samsung Galaxy Z Fold",
    description:
      "Foldable Mobile with large internal display and triple camera setup",
    category: "Electronics",
    subCategory: "Mobile",
    originalPrice: 70000,
    discount: 20,
    price: 56000,
    imageUrl: "https://i.ibb.co/gqNdh6f/el1.png",
    inStock: true,
    color: "Black",
    size: "7.6-inch main display",
  },
  {
    name: "Apple iMobile Orange Edition",
    description:
      "Premium Mobile with triple-lens camera and sleek orange design",
    category: "Electronics",
    subCategory: "Mobile",
    originalPrice: 45000,
    discount: 15,
    price: 38250,
    imageUrl: "https://i.ibb.co/ycmBVm6H/el2.png",
    inStock: true,
    color: "Orange",
    size: "6.1-inch display",
  },
  {
    name: "MacBook Pro",
    description:
      "High-performance laptop with sleek design and advanced display",
    category: "Electronics",
    subCategory: "Laptop",
    originalPrice: 120000,
    discount: 25,
    price: 90000,
    imageUrl: "https://i.ibb.co/LX3zpJsF/el3.png",
    inStock: false,
    color: "Gray",
    size: "16-inch display",
  },
  {
    name: "Realme Narzo 80 Lite",
    description:
      "Slim Mobile with massive battery, pulse light, and ultra volume",
    category: "Electronics",
    subCategory: "Mobile",
    originalPrice: 55000,
    discount: 10,
    price: 49500,
    imageUrl: "https://i.ibb.co/cKb8g26n/el4.png",
    inStock: true,
    color: "Gold",
    size: "6.6-inch display",
  },
  {
    name: "BenQ 4K UHD Monitor",
    description: "32-inch monitor with Wide Color P3 and USB-C power delivery",
    category: "Electronics",
    subCategory: "Monitor",
    originalPrice: 35000,
    discount: 15,
    price: 29750,
    imageUrl: "https://i.ibb.co/5X0RzqJD/el5.png",
    inStock: true,
    color: "Black",
    size: "32-inch display",
  },
  {
    name: "Procus One VR Headset",
    description:
      "Immersive VR headset with 40mm lenses and built-in touch button.",
    category: "Electronics",
    subCategory: "VR",
    originalPrice: 30000,
    discount: 10,
    price: 27000,
    imageUrl: "https://i.ibb.co/QFw1YSHK/el6.png",
    inStock: true,
    color: "Black",
    size: "Adjustable Headstrap",
  },
  {
    name: "Omega Fitness Tracker",
    description:
      "Slim fitness band with integrated heart rate and sleep tracking.",
    category: "Electronics",
    subCategory: "Watch",
    originalPrice: 15000,
    discount: 20,
    price: 12000,
    imageUrl: "https://i.ibb.co/DsmZk2q/el7.png",
    inStock: false,
    color: "Red",
    size: "Uni-size (Adjustable)",
  },
  {
    name: "Dahua Cube Security Camera",
    description:
      "Wireless indoor smart camera with motion detection and two-way audio.",
    category: "Electronics",
    subCategory: "Camera",
    originalPrice: 3500,
    discount: 10,
    price: 3150,
    imageUrl: "https://i.ibb.co/pvFFQZrk/el8.png",
    inStock: true,
    color: "White",
    size: "Compact Desktop",
  },
  {
    name: "OnePlus 7 Pro",
    description:
      "Flagship Mobile with Fluid AMOLED display and triple camera system.",
    category: "Electronics",
    subCategory: "Mobile",
    originalPrice: 60000,
    discount: 5,
    price: 57000,
    imageUrl: "https://i.ibb.co/QjDy4Lzj/el9.png",
    inStock: true,
    color: "Blue",
    size: "6.67-inch Display",
  },
  {
    name: "Zeta Sport Watch",
    description: "Circular dial rugged Watch with outdoor tracking features.",
    category: "Electronics",
    subCategory: "Watch",
    originalPrice: 12000,
    discount: 15,
    price: 10200,
    imageUrl: "https://i.ibb.co/QjKxCRhc/el10.png",
    inStock: false,
    color: "Green",
    size: "44mm Case",
  },
  {
    name: "Samsung Crystal 4K UHD TV",
    description:
      "43-inch Smart TV featuring 4K upscaling, HDR10+, and endless free content.",
    category: "Electronics",
    subCategory: "Smart TV",
    originalPrice: 40000,
    discount: 10,
    price: 36000,
    imageUrl: "https://i.ibb.co/1GRbzsVm/el11.png",
    inStock: true,
    color: "Black",
    size: "43-Inch",
  },
  {
    name: "Samsung QLED 4K AI TV",
    description:
      "65-inch QLED TV with Q4 AI Processor and Quantum Dot color technology.",
    category: "Electronics",
    subCategory: "Smart TV",
    originalPrice: 55000,
    discount: 15,
    price: 46750,
    imageUrl: "https://i.ibb.co/5gpBMbyf/el12.png",
    inStock: true,
    color: "Black",
    size: "65-Inch",
  },
  {
    name: "Realme Buds Air Series",
    description:
      "TWS earbuds featuring noise cancellation and ergonomic silicone tips.",
    category: "Electronics",
    subCategory: "Earbuds",
    originalPrice: 25000,
    discount: 10,
    price: 22500,
    imageUrl: "https://i.ibb.co/nMkjFKgT/el13.png",
    inStock: true,
    color: "Black",
    size: "In-ear",
  },
  {
    name: "Agaro Fast Charge Power Bank",
    description:
      "Portable power bank with LED digital display for real-time battery status.",
    category: "Electronics",
    subCategory: "Power Bank",
    originalPrice: 30000,
    discount: 5,
    price: 28500,
    imageUrl: "https://i.ibb.co/bjPCJkkc/el14.png",
    inStock: true,
    color: "Black",
    size: "10,000mAh",
  },
  {
    name: "boAt Rockerz HeadMobiles",
    description:
      "Premium over-ear wireless headMobiles with deep bass and comfort-fit earcups.",
    category: "Electronics",
    subCategory: "Mobile",
    originalPrice: 8000,
    discount: 20,
    price: 6400,
    imageUrl: "https://i.ibb.co/mC9pfvNj/el15.png",
    inStock: true,
    color: "Black",
    size: "Over-ear",
  },
  {
    name: "Zebronics Dash Wireless Mouse",
    description:
      "Slim, ergonomic 2.4GHz wireless mouse with a plug-and-play USB receiver.",
    category: "Electronics",
    subCategory: "Mouse",
    originalPrice: 1200,
    discount: 15,
    price: 1020,
    imageUrl: "https://i.ibb.co/mCK7YJyg/el16.png",
    inStock: true,
    color: ["Black", "Purple"],
    size: "Pocket-Sized",
  },
  {
    name: "Frameless LED Monitor",
    description:
      "Ultra-slim bezel-less monitor with a wide viewing angle and tilt-adjustable stand.",
    category: "Electronics",
    subCategory: "Monitor",
    originalPrice: 40000,
    discount: 10,
    price: 36000,
    imageUrl: "https://i.ibb.co/yFszHwYH/el17.png",
    inStock: true,
    color: "Blue",
    size: "24-Inch",
  },
  {
    name: "SpinBot Battlefield Keyboard",
    description:
      "Full-sized gaming keyboard with multi-color RGB backlighting and integrated wrist rest.",
    category: "Electronics",
    subCategory: "Keyboard",
    originalPrice: 6000,
    discount: 15,
    price: 5100,
    imageUrl: "https://i.ibb.co/np1Q6z3/el18.png",
    inStock: true,
    color: "Grey",
    size: "Full-Size (104 Keys)",
  },
  {
    name: "DualSense Wireless Controller",
    description:
      "Sony PlayStation 5 controller featuring haptic feedback and adaptive triggers.",
    category: "Electronics",
    subCategory: "Controller",
    originalPrice: 50000,
    discount: 5,
    price: 47500,
    imageUrl: "https://i.ibb.co/sJNy11Rf/el19.png",
    inStock: true,
    color: ["White", "Black"],
    size: "Standard",
  },
  {
    name: "Foldable Quadcopter Drone Kit",
    description:
      "Professional drone with 4K camera, dual batteries, and remote Mobile mount.",
    category: "Electronics",
    subCategory: "Drone",
    originalPrice: 45000,
    discount: 10,
    price: 40500,
    imageUrl: "https://i.ibb.co/FqBfNGWz/el20.png",
    inStock: true,
    color: "Grey",
    size: "Foldable Wings",
  },
  {
    name: "Amazon Echo Dot (4th Gen)",
    description:
      "Smart speaker with Alexa, featuring a sleek spherical design and rich bass.",
    category: "Electronics",
    subCategory: "Speaker",
    originalPrice: 4000,
    discount: 20,
    price: 3200,
    imageUrl: "https://i.ibb.co/zHD7mBRL/el21.png",
    inStock: true,
    color: "White",
    size: "3.9” Spherical",
  },
  {
    name: "Ambrane Stylo 20K Power Bank",
    description:
      "20000mAh high-capacity power bank with 20W fast charging and triple output.",
    category: "Electronics",
    subCategory: "Power Bank",
    originalPrice: 2500,
    discount: 15,
    price: 2125,
    imageUrl: "https://i.ibb.co/cSDs2Gb6/el22.png",
    inStock: true,
    color: "Blue",
    size: "20000mAh",
  },
  {
    name: "Amazon Fire TV Stick 4K",
    description:
      "Cinematic 4K streaming device with Alexa Voice Remote and Dolby Vision support.",
    category: "Electronics",
    subCategory: "Smart TV",
    originalPrice: 5000,
    discount: 10,
    price: 4500,
    imageUrl: "https://i.ibb.co/kVZyvHvr/el23.png",
    inStock: true,
    color: "Black",
    size: "Standard Stick",
  },
  {
    name: "Pigeon Hendy Hand Blender",
    description:
      "175W ergonomic hand blender with robust stainless steel blades for easy blending.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 3500,
    discount: 10,
    price: 3150,
    imageUrl: "https://i.ibb.co/7t132v5D/el24.png",
    inStock: true,
    color: ["Silver", "Black"],
    size: "Handheld",
  },
  {
    name: "Pigeon 16L Oven Toaster Grill",
    description:
      "Compact 16-liter OTG featuring adjustable temperature and timer for baking and grilling.",
    category: "Electronics",
    subCategory: "Oven",
    originalPrice: 8000,
    discount: 15,
    price: 6800,
    imageUrl: "https://i.ibb.co/v60pCz4s/el25.png",
    inStock: true,
    color: "Silver",
    size: "16 Liters",
  },
  {
    name: "Samsung Ecobubble Washer",
    description:
      "Fully automatic front-load washing machine with AI Control and Hygiene Steam technology.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 35000,
    discount: 20,
    price: 28000,
    imageUrl: "https://i.ibb.co/nvC3d1h/el26.png",
    inStock: true,
    color: "Silver",
    size: "8 kg",
  },
  {
    name: "Daikin Split AC",
    description:
      "1.5 Ton Inverter Split Air Conditioner with PM2.5 filter and Coanda Airflow for uniform cooling.",
    category: "Electronics",
    subCategory: "AC",
    originalPrice: 30000,
    discount: 15,
    price: 25500,
    imageUrl: "https://i.ibb.co/wNkncnZ7/el27.png",
    inStock: true,
    color: "White",
    size: "1.5 Ton",
  },
  {
    name: "Mi Robot Vacuum-Mop",
    description:
      "Smart cleaning robot with 2-in-1 sweeping and mopping features and LDS Laser Navigation.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 20000,
    discount: 10,
    price: 18000,
    imageUrl: "https://i.ibb.co/JWpjCMQf/el28.png",
    inStock: true,
    color: "Black",
    size: "Compact",
  },
  {
    name: "Samsung Solo Oven",
    description:
      "High-efficiency solo oven with Ceramic Enamel cavity for easy cleaning and durability.",
    category: "Electronics",
    subCategory: "Oven",
    originalPrice: 25000,
    discount: 10,
    price: 22500,
    imageUrl: "https://i.ibb.co/MD6666vW/el29.png",
    inStock: true,
    color: "Black",
    size: "23 Liters",
  },
  {
    name: "Samsung Bespoke Refrigerator",
    description:
      "Stylish double-door refrigerator with Twin Cooling Plus and customizable premium finish.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 60000,
    discount: 15,
    price: 51000,
    imageUrl: "https://i.ibb.co/JFwcr9kx/el30.png",
    inStock: true,
    color: "Blue",
    size: "345 Liters",
  },
  {
    name: "Pigeon Cruise Induction Cooktop",
    description:
      "Powerful 1800W induction cooktop with 7-segment LED display and high-grade crystal glass.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 4000,
    discount: 10,
    price: 3600,
    imageUrl: "https://i.ibb.co/tPCnWyr7/el31.png",
    inStock: true,
    color: "Black",
    size: "Portable",
  },
  {
    name: "Marshall Willen Speaker",
    description:
      "The mighty portable speaker built with a 2-inch full range driver and two passive radiators.",
    category: "Electronics",
    subCategory: "Speaker",
    originalPrice: 5000,
    discount: 10,
    price: 4500,
    imageUrl: "https://i.ibb.co/twH567Xq/el32.png",
    inStock: true,
    color: ["Black", "Brass"],
    size: "Compact",
  },
  {
    name: "Sony HT-S20R Home Theatre",
    description:
      "5.1 channel real surround sound system with rear speakers and a dedicated external subwoofer.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 20000,
    discount: 20,
    price: 16000,
    imageUrl: "https://i.ibb.co/5Xh2tn9C/el33.png",
    inStock: true,
    color: "Black",
    size: "5.1 Channel",
  },
  {
    name: "Samsung HW-B450 Soundbar",
    description:
      "Premium 2.1 channel soundbar featuring a wireless subwoofer and powerful Bass Boost mode.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 35000,
    discount: 10,
    price: 31500,
    imageUrl: "https://i.ibb.co/YFG7jr7b/el34.png",
    inStock: true,
    color: "Black",
    size: "2.1 Channel",
  },
  {
    name: "HP Smart Tank 580 Printer",
    description:
      "High-capacity wireless ink tank printer with scanning, copying, and smart mobile app support.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 12000,
    discount: 15,
    price: 10200,
    imageUrl: "https://i.ibb.co/MFwsNqd/el35.png",
    inStock: true,
    color: ["White", "Grey"],
    size: "A4 / All-in-One",
  },
  {
    name: "Canon imageFORMULA Production Document Scanner",
    description:
      "A high-performance scanner designed for high-volume document digitization.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 8000,
    discount: 10,
    price: 7200,
    imageUrl: "https://i.ibb.co/PztMmY4K/el36.png",
    inStock: true,
    color: "White",
    size: "Compact",
  },
  {
    name: "Logitech MX Master 3 Mouse",
    description:
      "Advanced ergonomic wireless mouse with flow control for multi-device usage.",
    category: "Electronics",
    subCategory: "Mouse",
    originalPrice: 6000,
    discount: 15,
    price: 5100,
    imageUrl: "https://i.ibb.co/mC8j2L3r/el37.png",
    inStock: true,
    color: "Black",
    size: "Ergonomic",
  },
  {
    name: "Razer Huntsman Mini Keyboard",
    description:
      "60% compact gaming keyboard with speed optical switches and customizable RGB lighting.",
    category: "Electronics",
    subCategory: "Keyboard",
    originalPrice: 10000,
    discount: 10,
    price: 9000,
    imageUrl: "https://i.ibb.co/yQGxkMDD/el38.png",
    inStock: true,
    color: "Black",
    size: "60% Compact",
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    description:
      "Wireless over-ear headphones with industry-leading noise cancellation and long battery life.",
    category: "Electronics",
    subCategory: "Headphones",
    originalPrice: 30000,
    discount: 15,
    price: 25500,
    imageUrl: "https://i.ibb.co/Kx0H6vV/el39.png",
    inStock: true,
    color: "Silver",
    size: "Over-Ear",
  },
  {
    name: "Bose QuietComfort Earbuds",
    description:
      "True wireless noise-canceling earbuds with high-fidelity audio.",
    category: "Electronics",
    subCategory: "Earbuds",
    originalPrice: 20000,
    discount: 10,
    price: 18000,
    imageUrl: "https://i.ibb.co/b3H9HzFb/el40.png",
    inStock: true,
    color: "White",
    size: "In-Ear",
  },
  {
    name: "Canon EOS R6 Camera",
    description:
      "Full-frame mirrorless camera with high-speed autofocus and 4K video recording.",
    category: "Electronics",
    subCategory: "Camera",
    originalPrice: 250000,
    discount: 20,
    price: 200000,
    imageUrl: "https://i.ibb.co/qy6Fh4Kv/el41.png",
    inStock: true,
    color: "Black",
    size: "Full-Frame",
  },
  {
    name: "GoPro Hero 11 Action Camera",
    description:
      "Rugged waterproof action camera with 5.3K video and HyperSmooth stabilization.",
    category: "Electronics",
    subCategory: "Camera",
    originalPrice: 50000,
    discount: 10,
    price: 45000,
    imageUrl: "https://i.ibb.co/hKXLPvFr/el42.png",
    inStock: true,
    color: "Black",
    size: "Compact",
  },
  {
    name: "DJI Mini 3 Pro Drone",
    description:
      "Ultra-lightweight drone with 4K HDR camera and tri-directional obstacle sensing.",
    category: "Electronics",
    subCategory: "Drone",
    originalPrice: 80000,
    discount: 15,
    price: 68000,
    imageUrl: "https://i.ibb.co/XV1sQd2r/el43.png",
    inStock: true,
    color: "White",
    size: "Compact",
  },
  {
    name: "Eufy RoboVac 30C Max",
    description:
      "Smart robotic vacuum cleaner with Wi-Fi connectivity and high suction power.",
    category: "Electronics",
    subCategory: "Appliances",
    originalPrice: 20000,
    discount: 10,
    price: 18000,
    imageUrl: "https://i.ibb.co/TvXrQ1Fn/el44.png",
    inStock: true,
    color: "Black",
    size: "Slim",
  },
  {
    name: "Philips Hue Smart Bulb",
    description:
      "Color-changing LED smart bulb with Alexa and Google Home compatibility.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 3500,
    discount: 15,
    price: 2975,
    imageUrl: "https://i.ibb.co/KVfnvnR7/el45.png",
    inStock: true,
    color: "White",
    size: "Standard",
  },
  {
    name: "Nest Learning Thermostat",
    description:
      "Smart thermostat with adaptive scheduling, energy history, and Wi-Fi control.",
    category: "Electronics",
    subCategory: "Accessories",
    originalPrice: 20000,
    discount: 10,
    price: 18000,
    imageUrl: "https://i.ibb.co/cFkmLPxD/el46.png",
    inStock: true,
    color: "White",
    size: "3rd Gen",
  },
  {
    name: "JBL Flip 6 Portable Speaker",
    description:
      "Waterproof Bluetooth speaker with high output and 12 hours battery life.",
    category: "Electronics",
    subCategory: "Speaker",
    originalPrice: 8000,
    discount: 15,
    price: 6800,
    imageUrl: "https://i.ibb.co/ZfQgw1Rr/el47.png",
    inStock: true,
    color: "Blue",
    size: "Portable",
  },
  {
    name: "Anker Soundcore Life P3",
    description:
      "True wireless earbuds with hybrid active noise cancellation and immersive sound.",
    category: "Electronics",
    subCategory: "Earbuds",
    originalPrice: 5000,
    discount: 10,
    price: 4500,
    imageUrl: "https://i.ibb.co/3s50TRMd/el48.png",
    inStock: true,
    color: "White",
    size: "In-Ear",
  },
  {
    name: "Apple Watch Series 9",
    description:
      "Advanced smartwatch with fitness tracking, ECG, and Always-On Retina display.",
    category: "Electronics",
    subCategory: "Watch",
    originalPrice: 50000,
    discount: 15,
    price: 42500,
    imageUrl: "https://i.ibb.co/J7xL5h7r/el49.png",
    inStock: true,
    color: "Red",
    size: "44mm",
  },
  {
    name: "Samsung Galaxy Buds Live",
    description:
      "True wireless earbuds with ergonomic design and Active Noise Cancellation.",
    category: "Electronics",
    subCategory: "Earbuds",
    originalPrice: 12000,
    discount: 10,
    price: 10800,
    imageUrl: "https://i.ibb.co/DkQZ8GLr/el50.png",
    inStock: true,
    color: "Black",
    size: "In-Ear",
  },
];
const imageUrls = [
  "https://files.catbox.moe/lkkc4z.png",
  "https://files.catbox.moe/8k9agj.png",
  "https://files.catbox.moe/vphy2c.png",
  "https://files.catbox.moe/ft1y2j.png",
  "https://files.catbox.moe/2tybbt.png",
  "https://files.catbox.moe/exv4hf.png",
  "https://files.catbox.moe/v6lm60.png",
  "https://files.catbox.moe/x0nv7p.png",
  "https://files.catbox.moe/qxdvzf.png",
  "https://files.catbox.moe/ajdx2o.png",
  "https://files.catbox.moe/e5kof3.png",
  "https://files.catbox.moe/7pexj8.png",
  "https://files.catbox.moe/bti8xw.png",
  "https://files.catbox.moe/j5evw8.png",
  "https://files.catbox.moe/q949gt.png",
  "https://files.catbox.moe/bma9u7.png",
  "https://files.catbox.moe/5ulxx2.png",
  "https://files.catbox.moe/6h0vm9.png",
  "https://files.catbox.moe/50earr.png",
  "https://files.catbox.moe/ck25aa.png",
  "https://files.catbox.moe/9u9pkz.png",
  "https://files.catbox.moe/2fqc87.png",
  "https://files.catbox.moe/mnyxll.png",
  "https://files.catbox.moe/f69chb.png",
  "https://files.catbox.moe/spg7df.png",
  "https://files.catbox.moe/ugtozr.png",
  "https://files.catbox.moe/r3rtrp.png",
  "https://files.catbox.moe/i427j2.png",
  "https://files.catbox.moe/0dkp3s.png",
  "https://files.catbox.moe/el3avs.png",
  "https://files.catbox.moe/b5ksqt.png",
  "https://files.catbox.moe/4l3qmf.png",
  "https://files.catbox.moe/iihohh.png",
  "https://files.catbox.moe/css3vn.png",
  "https://files.catbox.moe/dn5jci.png",
  "https://files.catbox.moe/op04vf.png",
  "https://files.catbox.moe/8ptsmi.png",
  "https://files.catbox.moe/lhu99b.png",
  "https://files.catbox.moe/q0vveb.png",
  "https://files.catbox.moe/3fbvzz.png",
  "https://files.catbox.moe/oisvqp.png",
  "https://files.catbox.moe/zqa4vc.png",
  "https://files.catbox.moe/3e9j5n.png",
  "https://files.catbox.moe/d7xaxz.png",
  "https://files.catbox.moe/pq3gji.png",
  "https://files.catbox.moe/ihu8dm.png",
  "https://files.catbox.moe/fm5s23.png",
  "https://files.catbox.moe/zxtk1d.png",
  "https://files.catbox.moe/5u6e60.png",
  "https://files.catbox.moe/9m55fh.png",
];

const updatedProducts = ElectronicsProducts.map((item, i) => ({
  ...item,
  imageUrl: imageUrls[i],
}));
mongoose
  
  .connect(MONGO_URI)
  .then(async () => {
    const insertedProducts = await Product.insertMany(updatedProducts);
    console.log(
      `✅ ${insertedProducts.length} products added to the database.`,
    );
    console.log("✅ Connected to MongoDB");
    await Product.deleteMany({ category: "Electronics" }); // remove old electronics
    await Product.insertMany(updatedProducts);
    console.log("✅ Electronics products seeded");
    mongoose.connection.close();
  })
  .catch((err) => console.error(err));