require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/product"); // adjust path if needed
const Homeproducts = [
  {
    name: "Triangle Side Table",
    description:
      "Triangle Side Table, Coffee Table for Living Room Sofa Side Table",
    category: "Home",
    subCategory: "Table",
    originalPrice: 1200,
    discount: 20,
    price: 960,
    imageUrl: "https://i.ibb.co/mr8RPsVp/frn1.png",
    inStock: true,
    materialType: "MDF",
    color: "Black",
    size: "45cm",
  },
  {
    name: "Wooden Book Shelf",
    description: "Amanda Engineered Wood Close Book Shelf",
    category: "Home",
    subCategory: "Bookshelf",
    originalPrice: 25000,
    discount: 15,
    price: 21250,
    imageUrl: "https://i.ibb.co/357R0WWY/frn2.png",
    inStock: true,
    materialType: "Particle Board",
    color: "Black",
    size: "70cm",
  },
  {
    name: "Wooden Stand",
    description: "Set Top Box Stand TV Stand WiFi Router Rack MDF",
    category: "Home",
    subCategory: "Stand",
    originalPrice: 5000,
    discount: 10,
    price: 4500,
    imageUrl: "https://i.ibb.co/7ts1B21x/frn3.png",
    inStock: true,
    materialType: "MDF (Medium Density Fiber)",
    color: "Brown",
    size: "20cm X 25 cm",
  },
  {
    name: "TV Wooden Set",
    description: "Engineered Wood TV Entertainment Unit",
    category: "Home",
    subCategory: "Wooden Set",
    originalPrice: 18000,
    discount: 20,
    price: 14400,
    imageUrl: "https://i.ibb.co/GQHTYXGP/frn4.png",
    inStock: true,
    materialType: "Particle Board",
    color: "Classic Wallnut",
    size: "55 inch",
  },
  {
    name: "Triangle Side Table",
    description:
      "Triangle Side Table, Coffee Table for Living Room Sofa Side Table",
    category: "Home",
    subCategory: "Table",
    originalPrice: 7000,
    discount: 25,
    price: 5250,
    imageUrl: "https://i.ibb.co/W4ZxvFFx/frn5.png",
    inStock: true,
    materialType: "MDF (Medium Density Fiber)",
    color: "White",
    size: "20cm X 45 cm",
  },
  {
    name: "Wooden Wall Shelves",
    description:
      "Zig Zag Home Decor Floating Display Rack Corner Hanging Wooden Wall Shelf (Number of Shelves - 5)",
    category: "Home",
    subCategory: "Wall Shelves",
    originalPrice: 8000,
    discount: 15,
    price: 6800,
    imageUrl: "https://i.ibb.co/d456zbB6/frn6.png",
    inStock: true,
    materialType: "MDF (Medium Density Fiber)",
    color: "Brown",
    size: "20cm X 20 cm X 49cm",
  },
  {
    name: "Door Mat",
    description: "Rubber Bathroom Mat (Multicolor, Free)",
    category: "Home",
    subCategory: "Mat",
    originalPrice: 3000,
    discount: 20,
    price: 2400,
    imageUrl: "https://i.ibb.co/q3KjfWD9/frn7.png",
    inStock: true,
    materialType: "Rubber",
    color: "Blue",
    size: "25 cm",
  },
  {
    name: "Wooden Wall Shelf",
    description: "Wooden wall shelf For Improvement (white)",
    category: "Home",
    subCategory: "Wall Shelf",
    originalPrice: 15000,
    discount: 10,
    price: 13500,
    imageUrl: "https://i.ibb.co/QVW6K9x/frn8.png",
    inStock: true,
    materialType: "Wooden",
    color: "White",
    size: "40cm X 25 cm",
  },
  {
    name: "Classic Rosewood Nightstand",
    description: "Elegant solid wood bedside table",
    category: "Home",
    subCategory: "Nightstand",
    originalPrice: 20000,
    discount: 15,
    price: 17000,
    imageUrl: "https://i.ibb.co/YT1SCH6H/frn9.png",
    inStock: true,
    materialType: "Sheesham / Rosewood",
    color: "Rich Walnut Brown",
    size: "45cm x 40cm x 55cm",
  },
  {
    name: "Geometric Twisted End Table",
    description: "A modern sculptural side table",
    category: "Home",
    subCategory: "End Table",
    originalPrice: 4500,
    discount: 10,
    price: 4050,
    imageUrl: "https://i.ibb.co/0yMG3Gbz/frn10.png",
    inStock: true,
    materialType: "Solid Acacia / Mango Wood",
    color: "Natural Oak Finish",
    size: "30cm x 30cm x 45cm",
  },
  {
    name: "Nordic Tripod Side Table",
    description:
      "Minimalist Scandinavian-style round end table and three tapered natural wood legs",
    category: "Home",
    subCategory: "Side Table",
    originalPrice: 9000,
    discount: 20,
    price: 7200,
    imageUrl: "https://i.ibb.co/LhNQTYGW/frn11.png",
    inStock: true,
    materialType: "Engineered Wood & Beech Wood",
    color: "White and Natural Oak",
    size: "40cm Diameter x 45cm Height",
  },
  {
    name: "Contemporary 6-Seater Dining Set",
    description: "Premium solid wood dining",
    category: "Home",
    subCategory: "Dining Set",
    originalPrice: 12000,
    discount: 15,
    price: 10200,
    imageUrl: "https://i.ibb.co/fVYsGCTx/frn12.png",
    inStock: true,
    materialType: "Solid Rubberwood",
    color: "Dark Walnut",
    size: "150cm x 90cm x 75cm",
  },
  {
    name: "Tripod Floor Lamp with Shelves",
    description:
      "Multifunctional 3-tier shelf floor lamp with a linen drum shade.",
    category: "Home",
    subCategory: "Lighting / Decor",
    originalPrice: 2500,
    discount: 10,
    price: 2250,
    imageUrl: "https://i.ibb.co/Y4FD7zM3/frn13.png",
    inStock: true,
    materialType: "Metal and Wood",
    color: "Black and Natural Wood",
    size: "160cm Height",
  },
  {
    name: "Modern S-Shaped Bedside Shelf",
    description: "Unique S-shaped open bookshelf and nightstand combo",
    category: "Home",
    subCategory: "Nightstand / Bookshelf",
    originalPrice: 5000,
    discount: 15,
    price: 4250,
    imageUrl: "https://i.ibb.co/vxfqHBLS/frn14.png",
    inStock: true,
    materialType: "High-Grade Engineered Wood",
    color: "Walnut",
    size: "50cm x 30cm x 60cm",
  },
  {
    name: "Handcrafted 4-Drawer Chest",
    description:
      "Traditional solid wood dresser featuring two small top drawers and two wide bottom drawers",
    category: "Home",
    subCategory: "Chest of Drawers",
    originalPrice: 18000,
    discount: 20,
    price: 14400,
    imageUrl: "https://i.ibb.co/gbLCcD7y/frn15.png",
    inStock: true,
    materialType: "Solid Sheesham Wood",
    color: "Honey Oak Finish",
    size: "85cm x 40cm x 90cm",
  },
  {
    name: "Adjustable Wooden Easy Chair",
    description: "Ergonomic folding lounge chair",
    category: "Home",
    subCategory: "Chairs & Recliners",
    originalPrice: 2000,
    discount: 10,
    price: 1800,
    imageUrl: "https://i.ibb.co/M5y1qnNV/frn16.png",
    inStock: true,
    materialType: "Natural Pine Wood & Cotton Fabric",
    color: "Natural Wood and Maroon",
    size: "60cm x 110cm x 90cm",
  },
  {
    name: "Diamond Quad Wall Shelf Set",
    description: "A stylish set of four diamond-shaped floating wall shelves",
    category: "Home",
    subCategory: "Wall Decor / Shelving",
    originalPrice: 7000,
    discount: 15,
    price: 5950,
    imageUrl: "https://i.ibb.co/hRwgZ60D/frn17.png",
    inStock: true,
    materialType: "High-Quality Engineered Wood",
    color: "Deep Walnut",
    size: "80cm x 80cm (Total Wall Coverage)",
  },
  {
    name: "Modern Minimalist Nightstand",
    description:
      "A sleek, contemporary bedside table featuring three open tiers",
    category: "Home",
    subCategory: "Nightstands",
    originalPrice: 3000,
    discount: 20,
    price: 2400,
    imageUrl: "https://i.ibb.co/MyBY4yWq/frn18.png",
    inStock: true,
    materialType: "MDF with Wood Veneer",
    color: "Dark Espresso",
    size: "45cm x 35cm x 50cm",
  },
  {
    name: "Multi-Utility Cupboard with Doors",
    description: "A versatile vertical storage cabinet",
    category: "Home",
    subCategory: "Storage Cabinets",
    originalPrice: 10000,
    discount: 25,
    price: 7500,
    imageUrl: "https://i.ibb.co/VcK71Xfw/frn19.png",
    inStock: true,
    materialType: "Laminated Particle Board",
    color: "Brown and White",
    size: "40cm x 30cm x 120cm",
  },
  {
    name: "5-Tier Rotating Kitchen Trolley",
    description: "Innovative rotating storage rack with mesh baskets",
    category: "Home",
    subCategory: "Kitchen Storage",
    originalPrice: 4500,
    discount: 10,
    price: 4050,
    imageUrl: "https://i.ibb.co/hxP15sJW/frn20.png",
    inStock: true,
    materialType: "Powder-Coated Carbon Steel",
    color: "Matte Black",
    size: "30cm x 30cm x 95cm",
  },
  {
    name: "Geometric Square Wall Shelves",
    description:
      "Set of 3 interlocking-style decorative wall shelves with oval side carvings.",
    category: "Home",
    subCategory: "Wall Decor",
    originalPrice: 12000,
    discount: 15,
    price: 10200,
    imageUrl: "https://i.ibb.co/LXbD8SY3/frn21.png",
    inStock: true,
    materialType: "Engineered Wood / MDF",
    color: "Walnut Brown",
    size: "Large: 30x30cm, Medium: 25x25cm, Small: 20x20cm",
  },
  {
    name: "Compact bedside Cabinet",
    description:
      "Minimalist white two-tier storage unit suitable for bedside or hallway use.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 8000,
    discount: 20,
    price: 6400,
    imageUrl: "https://i.ibb.co/7t26cXcN/frn22.png",
    inStock: true,
    materialType: "MDF with White Laminate",
    color: "White",
    size: "45cm x 40cm x 50cm",
  },
  {
    name: "Interlocking Floating Wall Shelf",
    description:
      "Modern dark wood floating shelf with multiple intersecting compartments.",
    category: "Home",
    subCategory: "Wall Decor",
    originalPrice: 6500,
    discount: 10,
    price: 5850,
    imageUrl: "https://i.ibb.co/WvV6Tv6x/frn23.png",
    inStock: true,
    materialType: "Engineered Wood",
    color: "Wenge / Dark Brown",
    size: "60cm x 10cm x 40cm",
  },
  {
    name: "Traditional Wooden Sofa Set",
    description:
      "Premium 6-seater wooden sofa set with grey cushions and matching coffee table.",
    category: "Home",
    subCategory: "Sofa Set",
    originalPrice: 11000,
    discount: 15,
    price: 9350,
    imageUrl: "https://i.ibb.co/NggNcndd/frn24.png",
    inStock: true,
    materialType: "Solid Teak Wood",
    color: "Natural Honey Finish",
    size: "3-Seater: 180cm, 2-Seater: 130cm, 1-Seater: 80cm",
  },
  {
    name: "3-Door Wardrobe with Mirror",
    description:
      "Spacious triple-door cupboard featuring a center mirror and silver handles.",
    category: "Home",
    subCategory: "Wardrobe",
    originalPrice: 3500,
    discount: 10,
    price: 3150,
    imageUrl: "https://i.ibb.co/tTTL8n9c/frn25.png",
    inStock: true,
    materialType: "Particle Board",
    color: "Dark Espresso",
    size: "120cm x 50cm x 180cm",
  },
  {
    name: "King Size Storage Bed",
    description:
      "Modern dark wood bed frame with integrated headboard shelving for books and decor.",
    category: "Home",
    subCategory: "Bed",
    originalPrice: 15000,
    discount: 15,
    price: 12750,
    imageUrl: "https://i.ibb.co/3Y1kPRzH/frn26.png",
    inStock: true,
    materialType: "Engineered Wood / MDF",
    color: "Wenge / Dark Espresso",
    size: "190cm x 210cm x 100cm",
  },
  {
    name: "Home Office Study Desk",
    description:
      "Dark brown workstation featuring a built-in hutch with bookshelves and a storage cabinet.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 8500,
    discount: 10,
    price: 7650,
    imageUrl: "https://i.ibb.co/nsd9gHKL/frn27.png",
    inStock: true,
    materialType: "MDF (Medium Density Fiber)",
    color: "Dark Walnut",
    size: "100cm x 50cm x 140cm",
  },
  {
    name: "Contemporary 3-Seater Sofa",
    description:
      "Stylish grey textured fabric sofa with black faux-leather armrests and accents.",
    category: "Home",
    subCategory: "Sofa",
    originalPrice: 18000,
    discount: 15,
    price: 15300,
    imageUrl: "https://i.ibb.co/zHsS7h6h/frn28.png",
    inStock: true,
    materialType: "Solid Wood Frame & Fabric",
    color: "Grey & Black",
    size: "185cm x 85cm x 80cm",
  },
  {
    name: "2-Door Shoe Cabinet",
    description:
      "Slim entryway storage unit with a wood-grain finish and silver vertical handles.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 4500,
    discount: 20,
    price: 3600,
    imageUrl: "https://i.ibb.co/j9L6k2Zx/frn29.png",
    inStock: true,
    materialType: "Particle Board with Laminate",
    color: "Charcoal Grey",
    size: "60cm x 30cm x 90cm",
  },
  {
    name: "Modular Step Bookshelf",
    description:
      "Versatile 10-cube tiered storage rack for books, office files, and home organization.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 5500,
    discount: 10,
    price: 4950,
    imageUrl: "https://i.ibb.co/KzscBG0Q/frn30.png",
    inStock: true,
    materialType: "Non-woven Fabric & Metal Pipe",
    color: "Black",
    size: "120cm x 30cm x 120cm",
  },
  {
    name: "Rattan Queen Bed Frame",
    description:
      "Boho-style bed with woven rattan headboard and base detailing.",
    category: "Home",
    subCategory: "Bed",
    originalPrice: 15000,
    discount: 20,
    price: 12000,
    imageUrl: "https://i.ibb.co/FkSSntch/frn31.png",
    inStock: true,
    materialType: "Solid Wood & Natural Rattan",
    color: "Natural Oak",
    size: "160cm x 205cm x 95cm",
  },
  {
    name: "Organic Shape Coffee Table",
    description:
      "Solid wood coffee table with a unique, sculpted pebble-like silhouette.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 5000,
    discount: 15,
    price: 4250,
    imageUrl: "https://i.ibb.co/FLXNtCqk/frn32.png",
    inStock: true,
    materialType: "Solid Acacia Wood",
    color: "Dark Walnut",
    size: "90cm x 60cm x 40cm",
  },
  {
    name: "Low-Profile Platform Sofa",
    description:
      "Modern charcoal sofa set on an extended wooden platform base.",
    category: "Home",
    subCategory: "Sofa",
    originalPrice: 7000,
    discount: 20,
    price: 5600,
    imageUrl: "https://i.ibb.co/qLcpgYwT/frn33.png",
    inStock: true,
    materialType: "Wood Base & Fabric Upholstery",
    color: "Charcoal & Mahogany",
    size: "210cm x 90cm x 75cm",
  },
  {
    name: "Blue Orthopedic Mattress",
    description:
      "Premium high-density foam mattress with a textured breathable cover.",
    category: "Home",
    subCategory: "Bedding",
    originalPrice: 2500,
    discount: 15,
    price: 2125,
    imageUrl: "https://i.ibb.co/Mxsft0M3/frn34.png",
    inStock: true,
    materialType: "Memory Foam & Fabric",
    color: "Navy Blue",
    size: "152cm x 198cm x 20cm",
  },
  {
    name: "Folding X-Frame Side Table",
    description:
      "Portable wooden folding table ideal for balconies or as a plant stand.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 5500,
    discount: 10,
    price: 4950,
    imageUrl: "https://i.ibb.co/x8JtZy99/frn35.png",
    inStock: true,
    materialType: "Sheesham Wood",
    color: "Antique Brown",
    size: "35cm x 35cm x 45cm",
  },
  {
    name: "Geometric Floating Shelves",
    description: "Modern interlocking square wall shelves in white.",
    category: "Home",
    subCategory: "Wall Decor",
    originalPrice: 3500,
    discount: 15,
    price: 2975,
    imageUrl: "https://i.ibb.co/whrXdQpS/frn36.png",
    inStock: true,
    materialType: "Engineered Wood",
    color: "White",
    size: "60cm x 60cm (Overall)",
  },
  {
    name: "Marble Pattern Laptop Desk",
    description: "Portable bed desk with tablet slot and cup holder.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 3000,
    discount: 10,
    price: 2700,
    imageUrl: "https://i.ibb.co/S4rZTJx2/frn37.png",
    inStock: true,
    materialType: "MDF & Metal",
    color: "White Marble",
    size: "60cm x 40cm",
  },
  {
    name: "Minimalist Study Set",
    description: "Natural pine wood desk with integrated shelving unit.",
    category: "Home",
    subCategory: "Office Furniture",
    originalPrice: 22000,
    discount: 15,
    price: 18700,
    imageUrl: "https://i.ibb.co/wrF04b8w/frn38.png",
    inStock: true,
    materialType: "Solid Pine Wood",
    color: "Natural",
    size: "120cm x 60cm",
  },
  {
    name: "Scandi Fabric Sofa & Ottoman",
    description: "Cream-colored 2-seater sofa with matching footrest.",
    category: "Home",
    subCategory: "Sofa",
    originalPrice: 4500,
    discount: 20,
    price: 3600,
    imageUrl: "https://i.ibb.co/HTQLL3sL/frn39.png",
    inStock: true,
    materialType: "Fabric & Oak",
    color: "Cream",
    size: "150cm x 85cm",
  },
  {
    name: "Modular Cube Bookshelf",
    description: "9-cube organizer with customizable drawer inserts.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 5000,
    discount: 15,
    price: 4250,
    imageUrl: "https://i.ibb.co/35666HMY/frn40.png",
    inStock: true,
    materialType: "Light Oak Veneer",
    color: "Light Wood",
    size: "110cm x 110cm",
  },
  {
    name: "Sheesham Wood Sideboard",
    description:
      "Multipurpose storage cabinet with drawers and a lattice door.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 6000,
    discount: 10,
    price: 5400,
    imageUrl: "https://i.ibb.co/xtNcH6Z1/frn41.png",
    inStock: true,
    materialType: "Solid Sheesham Wood",
    color: "Dark Walnut",
    size: "80cm x 40cm x 100cm",
  },
  {
    name: "Pedestal Accent Table",
    description: "Round wooden end table with a classic turned pedestal base.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 28000,
    discount: 15,
    price: 23800,
    imageUrl: "https://i.ibb.co/qM9RK7bm/frn42.png",
    inStock: true,
    materialType: "Mango Wood",
    color: "Honey Brown",
    size: "45cm Diameter",
  },
  {
    name: "Carved Magazine Table",
    description: "Antique style end table with floral carvings and side racks.",
    category: "Home",
    subCategory: "Table",
    originalPrice: 4000,
    discount: 10,
    price: 3600,
    imageUrl: "https://i.ibb.co/TMcVNfVr/frn43.png",
    inStock: true,
    materialType: "Solid Wood",
    color: "Distressed Teak",
    size: "40cm x 40cm x 45cm",
  },
  {
    name: "Heavy Duty Plastic Wardrobe",
    description: "Durable double-door storage almirah with a matte finish.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 2500,
    discount: 15,
    price: 2125,
    imageUrl: "https://i.ibb.co/hFjZ7KMG/frn44.png",
    inStock: true,
    materialType: "High-Grade Polymer",
    color: "Dark Brown",
    size: "75cm x 50cm x 180cm",
  },
  {
    name: "Slimline 2-Door Wardrobe",
    description: "Modern minimalist wardrobe with a natural wood grain finish.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 14000,
    discount: 20,
    price: 11200,
    imageUrl: "https://i.ibb.co/yFtZ77bL/frn45.png",
    inStock: true,
    materialType: "Engineered Wood",
    color: "Light Oak",
    size: "90cm x 55cm x 195cm",
  },
  {
    name: "Modern Queen Bed",
    description: "Elegant dual-tone bed frame with a curved headboard.",
    category: "Home",
    subCategory: "Bed",
    originalPrice: 18000,
    discount: 15,
    price: 15300,
    imageUrl: "https://i.ibb.co/VY1Pf4rS/frn46.png",
    inStock: true,
    materialType: "Engineered Wood",
    color: "Wenge & Oak",
    size: "160cm x 200cm",
  },
  {
    name: "Two-Door Shoe Cabinet",
    description: "Slim storage cabinet with a textured wood finish.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 9000,
    discount: 10,
    price: 8100,
    imageUrl: "https://i.ibb.co/TDgdcc98/frn47.png",
    inStock: true,
    materialType: "MDF with Laminate",
    color: "Dark Wood Grain",
    size: "80cm x 35cm x 120cm",
  },
  {
    name: "Blackout Eyelet Curtains",
    description: "Solid mauve-colored curtains with metal eyelets.",
    category: "Home",
    subCategory: "Furnishing",
    originalPrice: 2500,
    discount: 20,
    price: 2000,
    imageUrl: "https://i.ibb.co/zhDZWYH7/frn48.png",
    inStock: true,
    materialType: "Polyester",
    color: "Mauve",
    size: "150cm x 225cm",
  },
  {
    name: "Classic 5-Tier Bookshelf",
    description: "Sturdy open-shelf bookcase for home or office.",
    category: "Home",
    subCategory: "Storage",
    originalPrice: 5500,
    discount: 15,
    price: 4675,
    imageUrl: "https://i.ibb.co/mC4L3trw/frn49.png",
    inStock: true,
    materialType: "Solid Wood",
    color: "Honey Brown",
    size: "90cm x 30cm x 180cm",
  },
  {
    name: "Upholstered Daybed",
    description: "Versatile single bed that doubles as a lounge sofa.",
    category: "Home",
    subCategory: "Bed",
    originalPrice: 14000,
    discount: 10,
    price: 12600,
    imageUrl: "https://i.ibb.co/N6zKzw6b/frn50.png",
    inStock: true,
    materialType: "Engineered Wood & Fabric",
    color: "Charcoal Grey",
    size: "190cm x 90cm",
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("✅ MongoDB connected");
    await Product.deleteMany({ category: "Home" });
    await Product.insertMany(Homeproducts);
    console.log("✅ Home products seeded successfully");
    mongoose.connection.close();
  })
  .catch((err) => console.error(err));
