require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/product"); // your Product model

const mongoURI = process.env.MONGO_URI;

const WomenProducts = [
  {
    name: "Women Casual Ethnic Gown",
    description: "Women A-line White Midi/Calf Length Dress",
    category: "Women Ethnic",
    subCategory: "Gowns",
    originalPrice: 540,
    discount: 70,
    price: 162,
    imageUrl: "https://i.ibb.co/mC27cqMb/wmn1.png",
    inStock: true,
    color: " White ",
    size: " M , L , XL",
  },
  {
    name: "Women Beige Printed Kurta with Dupatta",
    description: "Women Self Design Viscose Rayon Straight Kurta(Yellow)",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 690,
    discount: 40,
    price: 414,
    imageUrl: "https://i.ibb.co/Ps44dRNT/wmn2.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Floral Print Casual Long Maxi Dress",
    description: "Women Floral Print Cotton Rayon Stitched Long Maxi Dress",
    category: "Women Western",
    subCategory: "Maxi Dresses",
    originalPrice: 759,
    discount: 80,
    price: 152,
    imageUrl: "https://i.ibb.co/bRg5YWjs/wmn3.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L",
  },
  {
    name: "Women Red Printed Sweater",
    description: "Women Solid Round Neck Red Printed Sweater",
    category: "Women Western",
    subCategory: "Sweaters",
    originalPrice: 1084,
    discount: 65,
    price: 379,
    imageUrl: "https://i.ibb.co/gLGm6gMh/wmn4.png",
    inStock: false,
    color: " Red ",
    size: " XS , S , L",
  },
  {
    name: "Women Relaxed Fit Sports Shorts",
    description: "Women Relaxed Fit Black Sports Shorts",
    category: "Women Sportswear",
    subCategory: "Shorts",
    originalPrice: 356,
    discount: 69,
    price: 110,
    imageUrl: "https://i.ibb.co/4gdYMXdj/wmn5.png",
    inStock: true,
    color: " Pink ",
    size: "S , M , L",
  },
  {
    name: "Women Classy Tracksuit",
    description: "Colorblock Women Tracksuit Suit",
    category: "Women Sportswear",
    subCategory: "Tracksuits",
    originalPrice: 1676,
    discount: 57,
    price: 720,
    imageUrl: "https://i.ibb.co/HT5zwdGG/wmn6.png",
    inStock: true,
    color: " Black ",
    size: "XS , S , M , L , XL",
  },
  {
    name: "Women Floral Print Casual Long Maxi Dress",
    description: "Women Solid White With Floral Print Casual Long Maxi Dress",
    category: "Women Western",
    subCategory: "Maxi Dresses",
    originalPrice: 756,
    discount: 35,
    price: 491,
    imageUrl: "https://i.ibb.co/TMgjzdc5/wmn7.png",
    inStock: false,
    color: " White ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Wide Leg Stretchable Jeans",
    description: "Women Loose Fit High Rise Wide Leg Stretchable Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 1436,
    discount: 60,
    price: 574,
    imageUrl: "https://i.ibb.co/ds76qx1K/wmn8.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L",
  },
  {
    name: "Women Floral Printed Kurta with Trousers & Dupatta",
    description:
      "Women Embroided, Floral Printed Kurta, Trouser/Pant & Dupatta",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 989,
    discount: 70,
    price: 297,
    imageUrl: "https://i.ibb.co/V0JFWvHm/wmn9.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL , XXL",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Georgette Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 758,
    discount: 70,
    price: 227,
    imageUrl: "https://i.ibb.co/gFvCcYRV/wmn10.png",
    inStock: true,
    color: " Maroon ",
    size: "S , M ",
  },
  {
    name: "Women Floral Print Kurta Pant with Dupatta",
    description: "Women Silk Blend Kurta Pant Dupatta Set",
    category: "Women Western",
    subCategory: "Kurta",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "https://i.ibb.co/tpV2f9Pm/wmn11.png",
    inStock: false,
    color: " Green ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Viscose Rayon Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 569,
    discount: 70,
    price: 171,
    imageUrl: "https://i.ibb.co/GY3mfhX/wmn12.png",
    inStock: true,
    color: " Pink ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Pure Cotton Kurta Salwar Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 647,
    discount: 65,
    price: 227,
    imageUrl: "https://i.ibb.co/PGtn8hBF/wmn13.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Viscose Rayon Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "https://i.ibb.co/k24p0nD9/wmn14.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Pure Cotton Kurta Salwar Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 580,
    discount: 60,
    price: 232,
    imageUrl: "https://i.ibb.co/C34QZjw1/wmn15.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Pure Cotton Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 697,
    discount: 10,
    price: 627,
    imageUrl: "https://i.ibb.co/MxZ7zLR3/wmn16.png",
    inStock: false,
    color: " Pink ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Silk Blend Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 967,
    discount: 75,
    price: 242,
    imageUrl: "https://i.ibb.co/zTTrKxv0/wmn17.png",
    inStock: true,
    color: " Cyan ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Silk Blend Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 391,
    discount: 80,
    price: 78,
    imageUrl: "https://i.ibb.co/9m74nqJR/wmn18.png",
    inStock: true,
    color: " Brown ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Pure Cotton Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 250,
    discount: 20,
    price: 200,
    imageUrl: "https://i.ibb.co/dsyFGRR7/wmn19.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Palazzo with Dupatta",
    description: "Women Silk Blend Cotton Blend Palazzo Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 2987,
    discount: 65,
    price: 1045,
    imageUrl: "https://i.ibb.co/hRPcSy7q/wmn20.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L",
  },
  {
    name: "Women Regular Shorts",
    description: "Women Short Line Sleeveless Black Shrug",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 560,
    discount: 30,
    price: 392,
    imageUrl: "https://i.ibb.co/39jBG2Gp/wmn21.png",
    inStock: false,
    color: " Black ",
    size: "XS , M , L",
  },
  {
    name: "Women Casual T-Shirt",
    description:
      "Tom N Jerry Women Graphic Print Round Neck Pure Cotton Black T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 670,
    discount: 40,
    price: 402,
    imageUrl: "https://i.ibb.co/8Gn247q/wmn22.jpg",
    inStock: true,
    color: " Black ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Casual T-Shirt",
    description: "Women Print Typography Round Neck Pure Cotton Red T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 637,
    discount: 20,
    price: 510,
    imageUrl: "https://i.ibb.co/NgWPNHFz/wmn23.png",
    inStock: false,
    color: " Red ",
    size: "S , M , XL",
  },
  {
    name: "Women Casual Western T-Shirt",
    description: "Women Round Neck Cotton Blend Orange T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 557,
    discount: 45,
    price: 306,
    imageUrl: "https://i.ibb.co/15JshJL/wmn24.png",
    inStock: true,
    color: " Orange ",
    size: " XS , S , M ",
  },
  {
    name: "Women Casual T-Shirt",
    description: "Women Round Neck Cotton Blend Black T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 794,
    discount: 75,
    price: 199,
    imageUrl: "https://i.ibb.co/zTZqZWP2/wmn25.png",
    inStock: false,
    color: " Black ",
    size: "S , M , L",
  },
  {
    name: "Women Casual T-Shirt",
    description: "Women Round Neck Rayon Black T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 452,
    discount: 25,
    price: 339,
    imageUrl: "https://i.ibb.co/LXkZ9fNt/wmn26.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Cotton Blend Kurta Pant Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 456,
    discount: 15,
    price: 387,
    imageUrl: "https://i.ibb.co/6kYQYJy/wmn27.png",
    inStock: false,
    color: " Pink ",
    size: "XS , L , XL",
  },
  {
    name: "Women Anarkali Kurta",
    description: "Women Chikan Embroidery Cotton Blend Anarkali Kurta (White)",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 657,
    discount: 50,
    price: 329,
    imageUrl: "https://i.ibb.co/LDnjpct2/wmn28.png",
    inStock: true,
    color: " White ",
    size: "S , M , L",
  },
  {
    name: "Women Regular Fitted Jeans",
    description: "Women Regular Mid Rise Blue Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 947,
    discount: 75,
    price: 237,
    imageUrl: "https://i.ibb.co/DPxnfnHH/wmn29.png",
    inStock: false,
    color: " Black ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Embroided Kurta, Legging & Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 499,
    discount: 65,
    price: 175,
    imageUrl: "https://i.ibb.co/4g0MC2Jn/wmn30.png",
    inStock: true,
    color: " Cyan ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Western Top",
    description: "Women Green Round Neck Top",
    category: "Women Western",
    subCategory: "Top",
    originalPrice: 567,
    discount: 45,
    price: 312,
    imageUrl: "https://i.ibb.co/KcvRgG14/wmn31.png",
    inStock: false,
    color: " Green ",
    size: "S , M , L",
  },
  {
    name: "Women Western Top",
    description: "Women White Round Neck Top",
    category: "Women Western",
    subCategory: "Top",
    originalPrice: 569,
    discount: 70,
    price: 171,
    imageUrl: "https://i.ibb.co/RTD2YLJ2/wmn32.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL",
  },

  {
    name: "Women High Rise Jeans",
    description: "Women Slim High Rise Black Jeans with White Strip",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 647,
    discount: 65,
    price: 227,
    imageUrl: "https://i.ibb.co/Zp400LRZ/wmn33.png",
    inStock: false,
    color: " Black ",
    size: " XS , S , M , L , XL",
  },
  {
    name: "Women Regular Fit Jeans",
    description: "Women Slim Mid Rise Black Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "https://i.ibb.co/Wp5H7xT1/wmn34.png",
    inStock: true,
    color: " Blue ",
    size: "S , M , L",
  },
  {
    name: "Women Regular Fit Jeans",
    description: "Women Regular Fit White Lycra Blend Trouser",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 580,
    discount: 60,
    price: 232,
    imageUrl: "https://i.ibb.co/DDsCF3dK/wmn35.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Casual Fit Jeans",
    description: "Women Skiny High Rise Light Blue Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 697,
    discount: 10,
    price: 627,
    imageUrl: "https://i.ibb.co/ccnZbbSh/wmn36.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L",
  },
  {
    name: "Women Casual Fit Jeans",
    description: "Women Slim Mid Rise Black Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 967,
    discount: 75,
    price: 242,
    imageUrl: "https://i.ibb.co/tw7QgrgT/wmn37.png",
    inStock: true,
    color: " Dark Blue ",
    size: "S , M ",
  },
  {
    name: "Women T-Shirt & Denim Combo",
    description: "V-Necked White T-shirt & Denim Skirt Set",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 391,
    discount: 80,
    price: 78,
    imageUrl: "https://i.ibb.co/wZqC941N/wmn38.png",
    inStock: true,
    color: " White ",
    size: "XS , M , L , XL",
  },
  {
    name: "Women Casual Fit Jeans",
    description: "Women Regular Low Rise Blue Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 250,
    discount: 20,
    price: 200,
    imageUrl: "https://i.ibb.co/0yVFPcc0/wmn39.png",
    inStock: false,
    color: " White ",
    size: "S , M , XL",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Pure Silk Kurta Pant/Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 2987,
    discount: 65,
    price: 1045,
    imageUrl: "https://i.ibb.co/SX8F9QKn/wmn40.png",
    inStock: true,
    color: " Purple ",
    size: "S , M , L",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Printed Kurta, Trouser/Pant & Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 560,
    discount: 30,
    price: 392,
    imageUrl: "https://i.ibb.co/mrjVFNCC/wmn41.png",
    inStock: false,
    color: " Red ",
    size: "S , M , L",
  },
  {
    name: "Women Casual Fit Jeans",
    description: "Women Skinny High Rise Black Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 670,
    discount: 40,
    price: 402,
    imageUrl: "https://i.ibb.co/0Vn3rcvH/wmn42.png",
    inStock: true,
    color: " Black ",
    size: "S , L , XL",
  },
  {
    name: "Women Casual Fit Jeans",
    description: "Women Skinny Mid Rise Black Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 637,
    discount: 20,
    price: 510,
    imageUrl: "https://i.ibb.co/h5J4rmW/wmn43.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L",
  },
  {
    name: "Women Casual Kurta Pant with Dupatta",
    description: "Printed Kurta, Trouser/Pant & Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 557,
    discount: 45,
    price: 306,
    imageUrl: "https://i.ibb.co/Df3C9yJP/wmn44.png",
    inStock: true,
    color: " Beige ",
    size: "S , M , L , XL",
  },
  {
    name: "Women's Kurta with Churidar Pyjama",
    description: "Women Viscose Rayon Kurta Dupatta Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 794,
    discount: 75,
    price: 199,
    imageUrl: "https://i.ibb.co/MDbCY086/wmn45.png",
    inStock: false,
    color: " White ",
    size: "S , M , L",
  },
  {
    name: "Women's Kurta Regular Silk Blend",
    description: "Women Silk Blend Kurta Pant Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 452,
    discount: 25,
    price: 339,
    imageUrl: "https://i.ibb.co/Xfzn98Sv/wmn46.png",
    inStock: true,
    color: " Yellow ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Kurta Pant with Dupatta",
    description: "Women Cotton Silk Kurta Pant Set",
    category: "Women Ethnic",
    subCategory: "Kurta",
    originalPrice: 456,
    discount: 15,
    price: 387,
    imageUrl: "https://i.ibb.co/Myvg0yXh/wmn47.png",
    inStock: false,
    color: " White ",
    size: "S , M , L",
  },
  {
    name: "Women Casual Oversized T-Shirt",
    description: "Women Cotton Round Neck T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 657,
    discount: 50,
    price: 329,
    imageUrl: "https://i.ibb.co/nNRDV8Gr/wmn48.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L , XL",
  },
  {
    name: "Women Cotton T-Shirt",
    description: "Women Cotton Blend Pink Round Neck T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 947,
    discount: 75,
    price: 237,
    imageUrl: "https://i.ibb.co/JWgP7MC4/wmn49.png",
    inStock: false,
    color: " Pink ",
    size: "S , M , L",
  },
  {
    name: "Women Printed Cotton T-Shirt",
    description: "Mickey Mouse Printed Round Neck T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirt",
    originalPrice: 499,
    discount: 65,
    price: 175,
    imageUrl: "https://i.ibb.co/SXx3LYBz/wmn50.png",
    inStock: true,
    color: " Maroon ",
    size: "S , M , L , XL",
  },
];

async function seedWomenProducts() {
  try {
    await mongoose.connect(mongoURI);
    console.log("✅ MongoDB connected");

    await Product.deleteMany({ category: /Women/i }); // remove old women's products
    await Product.insertMany(WomenProducts); // insert new ones
    console.log("✅ Women products seeded successfully");
  } catch (err) {
    console.error("❌ Error seeding women products:", err);
  } finally {
    await mongoose.connection.close();
  }
}

seedWomenProducts();
