const mongoose = require('mongoose');
const Product = require('./models/product'); // import Product model

const mongoURI = 'mongodb+srv://AHANAAWASTHI-MERN:MERN-Cluster!2802@mern-projects.rzxtk1k.mongodb.net/ecommerceDB?retryWrites=true&w=majority&appName=MERN-projects';

mongoose.connect(mongoURI)
    .then(() => console.log('✅ MongoDB connected successfully'))
    .catch(err => console.error('❌ MongoDB connection error:', err));

function calculateDiscountedPrice(originalPrice, discount) {
    return Math.round(originalPrice - (originalPrice * discount / 100));
}
const WomenProducts = [
  {
    name: "Women Casual Ethnic Gown",
    description: "Women Casual Ethnic Gown",
    category: "Women Ethnic",
    subCategory: "Gowns",
    originalPrice: 540,
    discount: 70,
    price: 162,
    imageUrl: "/images/Women/wmn1.png",
    inStock: true,
    color: " White ",
    size: " M , L , XL"
  },
  {
    name: "Women Beige Printed Kurta with Dupatta",
    description: "Women Beige Printed Kurta with Dupatta",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 690,
    discount: 40,
    price: 414,
    imageUrl: "/images/Women/wmn2.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Floral Print Casual Long Maxi Dress",
    description: "Women Floral Print Casual Long Maxi Dress",
    category: "Women Western",
    subCategory: "Maxi Dresses",
    originalPrice: 759,
    discount: 80,
    price: 152,
    imageUrl: "/images/Women/wmn3.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L"
  },
  {
    name: "Women Red Printed Sweater",
    description: "Women Red Printed Sweater",
    category: "Women Western",
    subCategory: "Sweaters",
    originalPrice: 1084,
    discount: 65,
    price: 379,
    imageUrl: "/images/Women/wmn4.png",
    inStock: false,
    color: " Red ",
    size: " XS , S , L"
  },
  {
    name: "Women Relaxed Fit Sports Shorts",
    description: "Women Relaxed Fit Sports Shorts",
    category: "Women Sportswear",
    subCategory: "Shorts",
    originalPrice: 356,
    discount: 69,
    price: 110,
    imageUrl: "/images/Women/wmn5.png",
    inStock: true,
    color: " Pink ",
    size: "S , M , L"
  },
  {
    name: "Women Classy Tracksuit",
    description: "Women Classy Tracksuit",
    category: "Women Sportswear",
    subCategory: "Tracksuits",
    originalPrice: 1676,
    discount: 57,
    price: 720,
    imageUrl: "/images/Women/wmn6.png",
    inStock: true,
    color: " Black ",
    size: "XS , S , M , L , XL"
  },
  {
    name: "Women Casual Shirt",
    description: "Women Casual Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 756,
    discount: 35,
    price: 491,
    imageUrl: "/images/Women/wmn7.png",
    inStock: false,
    color: " White ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Wide Leg Stretchable Jeans",
    description: "Women Wide Leg Stretchable Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 1436,
    discount: 60,
    price: 574,
    imageUrl: "/images/Women/wmn8.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L"
  },
  {
    name: "Women Floral Printed Kurta with Trousers & Dupatta",
    description: "Women Floral Printed Kurta with trousers & Dupatta",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 989,
    discount: 70,
    price: 297,
    imageUrl: "/images/Women/wmn9.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL , XXL"
  },
  {
    name: "Women Casual Wear",
    description: "Women Casual Wear",
    category: "Women Western",
    subCategory: "Tops",
    originalPrice: 758,
    discount: 70,
    price: 227,
    imageUrl: "/images/Women/wmn10.png",
    inStock: true,
    color: " Maroon ",
    size: "S , M "
  },
  {
    name: "Women Casual Oversized Shirt",
    description: "Women Casual Oversized Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "/images/Women/wmn11.png",
    inStock: false,
    color: " Green ",
    size: "S , M , L"
  },
  {
    name: "Women Loose Fit Dark Blue Jeans",
    description: "Women Loose Fit Dark Blue Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 569,
    discount: 70,
    price: 171,
    imageUrl: "/images/Women/wmn12.png",
    inStock: true,
    color: " Pink ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Loose Brown T-Shirt Cotton",
    description: "Women Casual Loose Brown T-Shirt Cotton",
    category: "Women Western",
    subCategory: "T-Shirts",
    originalPrice: 647,
    discount: 65,
    price: 227,
    imageUrl: "/images/Women/wmn13.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Regular Fit Formal Shirt",
    description: "Women Regular Fit Formal Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "/images/Women/wmn14.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Lined White T-Shirt",
    description: "Women Casual Lined White T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirts",
    originalPrice: 580,
    discount: 60,
    price: 232,
    imageUrl: "/images/Women/wmn15.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Loose Fit Jeans",
    description: "Women Casual Loose Fit Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 697,
    discount: 10,
    price: 627,
    imageUrl: "/images/Women/wmn16.png",
    inStock: false,
    color: " Pink ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Western Shirt",
    description: "Women Casual Western Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 967,
    discount: 75,
    price: 242,
    imageUrl: "/images/Women/wmn17.png",
    inStock: true,
    color: " Sky Blue ",
    size: "S , M , L"
  },
  {
    name: "Women Printed Track Suit",
    description: "Women Printed Track Suit",
    category: "Women Sportswear",
    subCategory: "Tracksuits",
    originalPrice: 391,
    discount: 80,
    price: 78,
    imageUrl: "/images/Women/wmn18.png",
    inStock: true,
    color: " Brown ",
    size: "S , M , L"
  },
  {
    name: "Women Socks",
    description: "Women Socks",
    category: "Women Accessories",
    subCategory: "Socks",
    originalPrice: 250,
    discount: 20,
    price: 200,
    imageUrl: "/images/Women/wmn19.png",
    inStock: false,
    color: " Yellow ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Casual T-Shirt and Jeans Combo",
    description: "Women Casual T-Shirt and Jeans Combo",
    category: "Women Western",
    subCategory: "Combos",
    originalPrice: 2987,
    discount: 65,
    price: 1045,
    imageUrl: "/images/Women/wmn20.png",
    inStock: true,
    color: " Green ",
    size: "S , M , L"
  },
  {
    name: "Women Regular Shorts",
    description: "Women Regular Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 560,
    discount: 30,
    price: 392,
    imageUrl: "/images/Women/wmn21.png",
    inStock: false,
    color: " White ",
    size: "XS , M , L"
  },
  {
    name: "Women Casual Shorts",
    description: "Women Casual Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 670,
    discount: 40,
    price: 402,
    imageUrl: "/images/Women/wmn22.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Loose Fit Checked Shirt",
    description: "Women Loose Fit Checked Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 637,
    discount: 20,
    price: 510,
    imageUrl: "/images/Women/wmn23.png",
    inStock: false,
    color: " Red ",
    size: "S , M , XL"
  },
  {
    name: "Women Casual Western Shorts",
    description: "Women Casual Western Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 557,
    discount: 45,
    price: 306,
    imageUrl: "/images/Women/wmn24.png",
    inStock: true,
    color: " Orange ",
    size: " XS , S , M "
  },
  {
    name: "Women's Kurta with Churidar Pyjama",
    description: "Women's Kurta with Churidar Pyjama",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 794,
    discount: 75,
    price: 199,
    imageUrl: "/images/Women/wmn25.png",
    inStock: false,
    color: " Black ",
    size: "S , M , L"
  },

  {
    name: "Women's Kurta Regular Cotton Blend",
    description: "Women's Kurta Regular Cotton Blend",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 452,
    discount: 25,
    price: 339,
    imageUrl: "/images/Women/wmn26.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Regular Fit Beach Shirt",
    description: "Women Regular Fit Beach Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 456,
    discount: 15,
    price: 387,
    imageUrl: "/images/Women/wmn27.png",
    inStock: false,
    color: " Pink ",
    size: "XS , L , XL"
  },
  {
    name: "Women Casual Oversized Shirt",
    description: "Women Casual Oversized Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 657,
    discount: 50,
    price: 329,
    imageUrl: "/images/Women/wmn28.png",
    inStock: true,
    color: " White ",
    size: "S , M , L"
  },
  {
    name: "Women Kurta and Pyjama Combo Cotton",
    description: "Women Kurta and Pyjama Combo Cotton",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 947,
    discount: 75,
    price: 237,
    imageUrl: "/images/Women/wmn29.png",
    inStock: false,
    color: " Black ",
    size: "S , M , L"
  },
  {
    name: "Women Winter Wear Full Sleeve Jacket",
    description: "Women Winter Wear Full Sleeve Jacket",
    category: "Women Western",
    subCategory: "Jackets",
    originalPrice: 499,
    discount: 65,
    price: 175,
    imageUrl: "/images/Women/wmn30.png",
    inStock: true,
    color: " Sky Blue ",
    size: "S , M , L , XL"
  },
  {
    name: "Women's Slim Fit Jacket",
    description: "Women's Slim Fit Jacket",
    category: "Women Western",
    subCategory: "Jackets",
    originalPrice: 567,
    discount: 45,
    price: 312,
    imageUrl: "/images/Women/wmn31.png",
    inStock: false,
    color: " Green ",
    size: "S , M , L"
  },
  {
    name: "Women's Casual Jacket",
    description: "Women's Casual Jacket",
    category: "Women Western",
    subCategory: "Jackets",
    originalPrice: 569,
    discount: 70,
    price: 171,
    imageUrl: "/images/Women/wmn32.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Casual Loose Brown T-Shirt Cotton",
    description: "Women Casual Loose Brown T-Shirt Cotton",
    category: "Women Western",
    subCategory: "T-Shirts",
    originalPrice: 647,
    discount: 65,
    price: 227,
    imageUrl: "/images/Women/wmn33.png",
    inStock: false,
    color: " Black ",
    size: " XS , S , M , L , XL"
  },
  {
    name: "Women Regular Fit Formal Shirt",
    description: "Women Regular Fit Formal Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "/images/Women/wmn34.png",
    inStock: true,
    color: " Blue ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Lined White T-Shirt",
    description: "Women Casual Lined White T-Shirt",
    category: "Women Western",
    subCategory: "T-Shirts",
    originalPrice: 580,
    discount: 60,
    price: 232,
    imageUrl: "/images/Women/wmn35.png",
    inStock: true,
    color: " White ",
    size: "S , M , L , XL"
  },
  {
    name: "Women Casual Loose Fit Jeans",
    description: "Women Casual Loose Fit Jeans",
    category: "Women Western",
    subCategory: "Jeans",
    originalPrice: 697,
    discount: 10,
    price: 627,
    imageUrl: "/images/Women/wmn36.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Western Shirt",
    description: "Women Casual Western Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 967,
    discount: 75,
    price: 242,
    imageUrl: "/images/Women/wmn37.png",
    inStock: true,
    color: " Dark Blue ",
    size: "S , M "
  },
  {
    name: "Women Printed Track Suit",
    description: "Women Printed Track Suit",
    category: "Women Sportswear",
    subCategory: "Tracksuits",
    originalPrice: 391,
    discount: 80,
    price: 78,
    imageUrl: "/images/Women/wmn38.png",
    inStock: true,
    color: " White ",
    size: "XS , M , L , XL"
  },
  {
    name: "Women Socks",
    description: "Women Socks",
    category: "Women Accessories",
    subCategory: "Socks",
    originalPrice: 250,
    discount: 20,
    price: 200,
    imageUrl: "/images/Women/wmn39.png",
    inStock: false,
    color: " White ",
    size: "S , M , XL"
  },
  {
    name: "Women Casual T-Shirt and Jeans Combo",
    description: "Women Casual T-Shirt and Jeans Combo",
    category: "Women Western",
    subCategory: "Combos",
    originalPrice: 2987,
    discount: 65,
    price: 1045,
    imageUrl: "/images/Women/wmn40.png",
    inStock: true,
    color: " Purple ",
    size: "S , M , L"
  },
  {
    name: "Women Regular Shorts",
    description: "Women Regular Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 560,
    discount: 30,
    price: 392,
    imageUrl: "/images/Women/wmn41.png",
    inStock: false,
    color: " Red ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Shorts",
    description: "Women Casual Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 670,
    discount: 40,
    price: 402,
    imageUrl: "/images/Women/wmn42.png",
    inStock: true,
    color: " Black ",
    size: "S , L , XL"
  },
  {
    name: "Women Loose Fit Checked Shirt",
    description: "Women Loose Fit Checked Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 637,
    discount: 20,
    price: 510,
    imageUrl: "/images/Women/wmn43.png",
    inStock: false,
    color: " Blue ",
    size: "S , M , L"
  },
  {
    name: "Women Casual Western Shorts",
    description: "Women Casual Western Shorts",
    category: "Women Western",
    subCategory: "Shorts",
    originalPrice: 557,
    discount: 45,
    price: 306,
    imageUrl: "/images/Women/wmn44.png",
    inStock: true,
    color: " Cream ",
    size: "S , M , L , XL"
  },
  {
    name: "Women's Kurta with Churidar Pyjama",
    description: "Women's Kurta with Churidar Pyjama",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 794,
    discount: 75,
    price: 199,
    imageUrl: "/images/Women/wmn45.png",
    inStock: false,
    color: " Red ",
    size: "S , M , L , XL"
  },
  {
    name: "Women's Kurta Regular Cotton Blend",
    description: "Women's Kurta Regular Cotton Blend",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 452,
    discount: 25,
    price: 339,
    imageUrl: "/images/Women/wmn46.png",
    inStock: true,
    color: " Yellow ",
    size: "S , M , L"
  },
  {
    name: "Women Regular Fit Beach Shirt",
    description: "Women Regular Fit Beach Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 456,
    discount: 15,
    price: 387,
    imageUrl: "/images/Women/wmn47.png",
    inStock: false,
    color: " Pink ",
    size: " XS , S , M , L , XL"
  },
  {
    name: "Women Casual Oversized Shirt",
    description: "Women Casual Oversized Shirt",
    category: "Women Western",
    subCategory: "Shirts",
    originalPrice: 657,
    discount: 50,
    price: 329,
    imageUrl: "/images/Women/wmn48.png",
    inStock: true,
    color: " Brown ",
    size: " XS , S , M , L"
  },
  {
    name: "Women Kurta and Pyjama Combo Cotton",
    description: "Women Kurta and Pyjama Combo Cotton",
    category: "Women Ethnic",
    subCategory: "Kurtas",
    originalPrice: 457,
    discount: 50,
    price: 228,
    imageUrl: "/images/Women/wmn49.png",
    inStock: true,
    color: " Black ",
    size: "S , M , L"
  },
  {
    name: "Women Winter Wear Full Sleeve Jacket",
    description: "Women Winter Wear Full Sleeve Jacket",
    category: "Women Western",
    subCategory: "Jackets",
    originalPrice: 457,
    discount: 50,
    price: 229,
    imageUrl: "/images/Women/wmn50.png",
    inStock: false,
    color: " Maroon ",
    size: "S , M , L , XL"
  }
];

// Seed function
async function seedWomenProducts() {
    try {
await Product.deleteMany({ category: /Women/i }); // ✅ deletes only women's products
        await Product.insertMany(WomenProducts); // Insert new
        console.log('✅ Women products seeded successfully');
    } catch (err) {
        console.error('❌ Error seeding women products:', err);
    } finally {
        mongoose.connection.close();
    }
}

seedWomenProducts();
